apiVersion: "application.giantswarm.io/v1alpha1"
kind: AppCatalog
metadata:
  name: "{{ .Values.appCatalog.name }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    app-operator.giantswarm.io/version: "{{ .Values.appOperator.version }}"
spec:
  title: "{{ .Values.appCatalog.title }}"
  description: "{{ .Values.appCatalog.description }}"
  logoURL: "{{ .Values.appCatalog.logoUrl }}"
  storage:
    type: "{{ .Values.appCatalog.storage.type }}"
    URL: "{{ .Values.appCatalog.storage.url }}"
  {{- if .Values.appCatalog.config }}
  config:
    {{- if .Values.appCatalog.config.configMap }}
    configMap:
      name: "{{ .Values.appcatalog.config.configMap.name }}"
      namespace: "{{ .Values.appcatalog.config.configMap.namespace }}"
    {{- end }}
    {{- if .Values.appCatalog.config.secret }}
    secret:
      name: "{{ .Values.appCatalog.config.secret.name }}"
      namespace: "{{ .Values.appCatalog.config.secret.namespace }}"
    {{- end }}
  {{- end }}
