{{ if .Values.app.config.secret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: giantswarm
data:
  values: {{ toYaml .Values.secret.values | b64enc | quote }}
type: Opaque
{{ end }}
