apiVersion: v1
kind: Secret
metadata:
  labels:
    clusterID: "{{.Values.clusterName}}"
    clusterKey: "encryption"
  name: "{{.Values.clusterName}}-encryption"
  namespace: default
type: Opaque
data:
  encryption: "{{.Values.encryptionKey}}"
