apiVersion: cluster.x-k8s.io/v1alpha4
kind: Cluster
metadata:
  annotations:
    cluster.giantswarm.io/description: production
    release.giantswarm.io/last-deployed-version: 15.1.1
  labels:
    azure-operator.giantswarm.io/version: 5.8.1
    cluster-operator.giantswarm.io/version: 0.27.1
    cluster.x-k8s.io/cluster-name: x4j3p
    giantswarm.io/cluster: x4j3p
    giantswarm.io/organization: giantswarm
    release.giantswarm.io/version: 15.1.1
  name: x4j3p
  namespace: org-giantswarm
spec:
  clusterNetwork:
    apiServerPort: 443
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 172.31.0.0/16
  controlPlaneEndpoint:
    host: api.example.com
    port: 443
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AzureMachine
    name: x4j3p-master-0
    namespace: org-giantswarm
    resourceVersion: "374040211"
    uid: 177991ca-5de0-48f6-a956-47abcb218a3b
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AzureCluster
    name: x4j3p
    namespace: org-giantswarm
    resourceVersion: "374040188"
    uid: 01d6767e-c394-43a7-bf17-2eaf11e80dcb
