apiVersion: exp.cluster.x-k8s.io/v1alpha3
kind: MachinePool
metadata:
  annotations:
    cluster.k8s.io/cluster-api-autoscaler-node-group-max-size: "10"
    cluster.k8s.io/cluster-api-autoscaler-node-group-min-size: "3"
    machine-pool.giantswarm.io/name: Unnamed node pool
    release.giantswarm.io/last-deployed-version: 15.1.1
  labels:
    azure-operator.giantswarm.io/version: 5.8.1
    cluster-operator.giantswarm.io/version: 0.27.1
    cluster.x-k8s.io/cluster-name: x4j3p
    giantswarm.io/cluster: x4j3p
    giantswarm.io/machine-pool: q5k7t
    giantswarm.io/organization: giantswarm
    release.giantswarm.io/version: 15.1.1
  name: q5k7t
  namespace: org-giantswarm
spec:
  clusterName: x4j3p
  failureDomains:
  - "2"
  minReadySeconds: 0
  providerIDList:
    - azure:///subscriptions/aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee/resourceGroups/mmh5x/providers/Microsoft.Compute/virtualMachineScaleSets/nodepool-w86vu/virtualMachines/0
    - azure:///subscriptions/aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee/resourceGroups/mmh5x/providers/Microsoft.Compute/virtualMachineScaleSets/nodepool-w86vu/virtualMachines/1
    - azure:///subscriptions/aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee/resourceGroups/mmh5x/providers/Microsoft.Compute/virtualMachineScaleSets/nodepool-w86vu/virtualMachines/2
  replicas: 3
  template:
    metadata: {}
    spec:
      bootstrap:
        configRef:
          apiVersion: core.giantswarm.io/v1alpha1
          kind: Spark
          name: q5k7t
          namespace: org-giantswarm
          resourceVersion: "374040263"
          uid: a4f5af79-1354-4c99-a68b-433deaff2ede
      clusterName: x4j3p
      infrastructureRef:
        apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
        kind: AzureMachinePool
        name: q5k7t
        namespace: org-giantswarm
        resourceVersion: "374040262"
        uid: 4d1e7420-53a8-4a38-8a2c-0bd30f93a593
