apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AzureCluster
metadata:
  labels:
    azure-operator.giantswarm.io/version: 5.3.1
    cluster-operator.giantswarm.io/version: 0.23.22
    cluster.x-k8s.io/cluster-name: mmh5x
    giantswarm.io/cluster: mmh5x
    giantswarm.io/organization: giantswarm
    release.giantswarm.io/version: 14.1.0
  name: mmh5x
  namespace: org-giantswarm
spec:
  controlPlaneEndpoint:
    host: api.mmh5x.k8s.ghost.westeurope.azure.gigantic.io
    port: 443
  location: westeurope
  networkSpec:
    apiServerLB:
      frontendIPs:
        - name: mmh5x-API-PublicLoadBalancer-Frontend
      name: mmh5x-API-PublicLoadBalancer
      sku: Standard
      type: Public
    subnets:
      - cidrBlocks:
          - 10.3.3.0/24
        id: /subscriptions/aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee/resourceGroups/mmh5x/providers/Microsoft.Network/virtualNetworks/mmh5x-VirtualNetwork/subnets/w86vu
        name: w86vu
        role: node
        routeTable: {}
        securityGroup: {}
      - name: mmh5x-VirtualNetwork-MasterSubnet
        role: control-plane
        routeTable: {}
        securityGroup: {}
    vnet:
      cidrBlocks:
        - 10.3.0.0/16
      name: mmh5x-VirtualNetwork
      resourceGroup: mmh5x
  resourceGroup: mmh5x
