apiVersion: application.giantswarm.io/v1alpha2
kind: App
metadata:
  annotations:
    giantswarm.io/docs: https://docs.giantswarm.io/reference/cp-k8s-api/apps.application.giantswarm.io/
  creationTimestamp: null
  name: ier2s
spec:
  availabilityZones:
  - eu-central-1a
  - eu-central-1b
  - eu-central-1c
  instanceType: m4.xlarge
