apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AzureMachine
metadata:
  labels:
    azure-operator.giantswarm.io/version: 5.3.1
    cluster.x-k8s.io/cluster-name: mmh5x
    cluster.x-k8s.io/control-plane: "true"
    giantswarm.io/cluster: mmh5x
    giantswarm.io/organization: giantswarm
    release.giantswarm.io/version: 14.1.0
  name: mmh5x-master-0
  namespace: org-giantswarm
spec:
  availabilityZone: {}
  failureDomain: "3"
  identity: None
  image:
    marketplace:
      offer: flatcar-container-linux-free
      publisher: kinvolk
      sku: stable
      thirdPartyImage: false
      version: 2345.3.1
  location: westeurope
  osDisk:
    cachingType: ReadWrite
    diskSizeGB: 50
    managedDisk:
      storageAccountType: Premium_LRS
    osType: Linux
  sshPublicKey: ""
  vmSize: Standard_D4s_v3
