apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: g8scontrolplanes.infrastructure.giantswarm.io
  namespace: {{ .Values.namespace }}
spec:
  conversion:
    strategy: None
  group: infrastructure.giantswarm.io
  names:
    kind: G8sControlPlane
    plural: g8scontrolplanes
    singular: g8scontrolplane
  scope: Namespaced
  subresources:
    status: {}
  versions:
    -
      name: v1alpha1
      served: false
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            type: object
            spec:
              type: object
              properties:
                replicas:
                  type: integer
    -
      name: v1alpha2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            type: object
            spec:
              type: object
              properties:
                infrastructureRef:
                  type: object
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
                    namespace:
                      type: string
                replicas:
                  type: integer
                  enum:
                    - 1
                    - 3
