/*
Copyright 2020 Giant Swarm GmbH.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"

	v1alpha1 "github.com/giantswarm/apiextensions/v2/pkg/apis/application/v1alpha1"
	scheme "github.com/giantswarm/apiextensions/v2/pkg/clientset/versioned/scheme"
)

// AppCatalogEntriesGetter has a method to return a AppCatalogEntryInterface.
// A group's client should implement this interface.
type AppCatalogEntriesGetter interface {
	AppCatalogEntries() AppCatalogEntryInterface
}

// AppCatalogEntryInterface has methods to work with AppCatalogEntry resources.
type AppCatalogEntryInterface interface {
	Create(ctx context.Context, appCatalogEntry *v1alpha1.AppCatalogEntry, opts v1.CreateOptions) (*v1alpha1.AppCatalogEntry, error)
	Update(ctx context.Context, appCatalogEntry *v1alpha1.AppCatalogEntry, opts v1.UpdateOptions) (*v1alpha1.AppCatalogEntry, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.AppCatalogEntry, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.AppCatalogEntryList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AppCatalogEntry, err error)
	AppCatalogEntryExpansion
}

// appCatalogEntries implements AppCatalogEntryInterface
type appCatalogEntries struct {
	client rest.Interface
}

// newAppCatalogEntries returns a AppCatalogEntries
func newAppCatalogEntries(c *ApplicationV1alpha1Client) *appCatalogEntries {
	return &appCatalogEntries{
		client: c.RESTClient(),
	}
}

// Get takes name of the appCatalogEntry, and returns the corresponding appCatalogEntry object, and an error if there is any.
func (c *appCatalogEntries) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AppCatalogEntry, err error) {
	result = &v1alpha1.AppCatalogEntry{}
	err = c.client.Get().
		Resource("appcatalogentries").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AppCatalogEntries that match those selectors.
func (c *appCatalogEntries) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AppCatalogEntryList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AppCatalogEntryList{}
	err = c.client.Get().
		Resource("appcatalogentries").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested appCatalogEntries.
func (c *appCatalogEntries) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("appcatalogentries").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a appCatalogEntry and creates it.  Returns the server's representation of the appCatalogEntry, and an error, if there is any.
func (c *appCatalogEntries) Create(ctx context.Context, appCatalogEntry *v1alpha1.AppCatalogEntry, opts v1.CreateOptions) (result *v1alpha1.AppCatalogEntry, err error) {
	result = &v1alpha1.AppCatalogEntry{}
	err = c.client.Post().
		Resource("appcatalogentries").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(appCatalogEntry).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a appCatalogEntry and updates it. Returns the server's representation of the appCatalogEntry, and an error, if there is any.
func (c *appCatalogEntries) Update(ctx context.Context, appCatalogEntry *v1alpha1.AppCatalogEntry, opts v1.UpdateOptions) (result *v1alpha1.AppCatalogEntry, err error) {
	result = &v1alpha1.AppCatalogEntry{}
	err = c.client.Put().
		Resource("appcatalogentries").
		Name(appCatalogEntry.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(appCatalogEntry).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the appCatalogEntry and deletes it. Returns an error if one occurs.
func (c *appCatalogEntries) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("appcatalogentries").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *appCatalogEntries) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("appcatalogentries").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched appCatalogEntry.
func (c *appCatalogEntries) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AppCatalogEntry, err error) {
	result = &v1alpha1.AppCatalogEntry{}
	err = c.client.Patch(pt).
		Resource("appcatalogentries").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
