/*
Copyright 2020 Giant Swarm GmbH.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha3

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"

	v1alpha3 "github.com/giantswarm/apiextensions/pkg/apis/infrastructure/v1alpha3"
	scheme "github.com/giantswarm/apiextensions/pkg/clientset/versioned/scheme"
)

// AzureClustersGetter has a method to return a AzureClusterInterface.
// A group's client should implement this interface.
type AzureClustersGetter interface {
	AzureClusters(namespace string) AzureClusterInterface
}

// AzureClusterInterface has methods to work with AzureCluster resources.
type AzureClusterInterface interface {
	Create(*v1alpha3.AzureCluster) (*v1alpha3.AzureCluster, error)
	Update(*v1alpha3.AzureCluster) (*v1alpha3.AzureCluster, error)
	UpdateStatus(*v1alpha3.AzureCluster) (*v1alpha3.AzureCluster, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha3.AzureCluster, error)
	List(opts v1.ListOptions) (*v1alpha3.AzureClusterList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha3.AzureCluster, err error)
	AzureClusterExpansion
}

// azureClusters implements AzureClusterInterface
type azureClusters struct {
	client rest.Interface
	ns     string
}

// newAzureClusters returns a AzureClusters
func newAzureClusters(c *InfrastructureV1alpha3Client, namespace string) *azureClusters {
	return &azureClusters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the azureCluster, and returns the corresponding azureCluster object, and an error if there is any.
func (c *azureClusters) Get(name string, options v1.GetOptions) (result *v1alpha3.AzureCluster, err error) {
	result = &v1alpha3.AzureCluster{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("azureclusters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AzureClusters that match those selectors.
func (c *azureClusters) List(opts v1.ListOptions) (result *v1alpha3.AzureClusterList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha3.AzureClusterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("azureclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested azureClusters.
func (c *azureClusters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("azureclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a azureCluster and creates it.  Returns the server's representation of the azureCluster, and an error, if there is any.
func (c *azureClusters) Create(azureCluster *v1alpha3.AzureCluster) (result *v1alpha3.AzureCluster, err error) {
	result = &v1alpha3.AzureCluster{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("azureclusters").
		Body(azureCluster).
		Do().
		Into(result)
	return
}

// Update takes the representation of a azureCluster and updates it. Returns the server's representation of the azureCluster, and an error, if there is any.
func (c *azureClusters) Update(azureCluster *v1alpha3.AzureCluster) (result *v1alpha3.AzureCluster, err error) {
	result = &v1alpha3.AzureCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("azureclusters").
		Name(azureCluster.Name).
		Body(azureCluster).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *azureClusters) UpdateStatus(azureCluster *v1alpha3.AzureCluster) (result *v1alpha3.AzureCluster, err error) {
	result = &v1alpha3.AzureCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("azureclusters").
		Name(azureCluster.Name).
		SubResource("status").
		Body(azureCluster).
		Do().
		Into(result)
	return
}

// Delete takes name of the azureCluster and deletes it. Returns an error if one occurs.
func (c *azureClusters) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("azureclusters").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *azureClusters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("azureclusters").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched azureCluster.
func (c *azureClusters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha3.AzureCluster, err error) {
	result = &v1alpha3.AzureCluster{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("azureclusters").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
