/*
Copyright 2020 Giant Swarm GmbH.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha3

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"

	v1alpha3 "github.com/giantswarm/apiextensions/pkg/apis/infrastructure/v1alpha3"
	scheme "github.com/giantswarm/apiextensions/pkg/clientset/versioned/scheme"
)

// AzureMachinePoolsGetter has a method to return a AzureMachinePoolInterface.
// A group's client should implement this interface.
type AzureMachinePoolsGetter interface {
	AzureMachinePools(namespace string) AzureMachinePoolInterface
}

// AzureMachinePoolInterface has methods to work with AzureMachinePool resources.
type AzureMachinePoolInterface interface {
	Create(*v1alpha3.AzureMachinePool) (*v1alpha3.AzureMachinePool, error)
	Update(*v1alpha3.AzureMachinePool) (*v1alpha3.AzureMachinePool, error)
	UpdateStatus(*v1alpha3.AzureMachinePool) (*v1alpha3.AzureMachinePool, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha3.AzureMachinePool, error)
	List(opts v1.ListOptions) (*v1alpha3.AzureMachinePoolList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha3.AzureMachinePool, err error)
	AzureMachinePoolExpansion
}

// azureMachinePools implements AzureMachinePoolInterface
type azureMachinePools struct {
	client rest.Interface
	ns     string
}

// newAzureMachinePools returns a AzureMachinePools
func newAzureMachinePools(c *InfrastructureV1alpha3Client, namespace string) *azureMachinePools {
	return &azureMachinePools{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the azureMachinePool, and returns the corresponding azureMachinePool object, and an error if there is any.
func (c *azureMachinePools) Get(name string, options v1.GetOptions) (result *v1alpha3.AzureMachinePool, err error) {
	result = &v1alpha3.AzureMachinePool{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("azuremachinepools").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AzureMachinePools that match those selectors.
func (c *azureMachinePools) List(opts v1.ListOptions) (result *v1alpha3.AzureMachinePoolList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha3.AzureMachinePoolList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("azuremachinepools").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested azureMachinePools.
func (c *azureMachinePools) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("azuremachinepools").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a azureMachinePool and creates it.  Returns the server's representation of the azureMachinePool, and an error, if there is any.
func (c *azureMachinePools) Create(azureMachinePool *v1alpha3.AzureMachinePool) (result *v1alpha3.AzureMachinePool, err error) {
	result = &v1alpha3.AzureMachinePool{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("azuremachinepools").
		Body(azureMachinePool).
		Do().
		Into(result)
	return
}

// Update takes the representation of a azureMachinePool and updates it. Returns the server's representation of the azureMachinePool, and an error, if there is any.
func (c *azureMachinePools) Update(azureMachinePool *v1alpha3.AzureMachinePool) (result *v1alpha3.AzureMachinePool, err error) {
	result = &v1alpha3.AzureMachinePool{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("azuremachinepools").
		Name(azureMachinePool.Name).
		Body(azureMachinePool).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *azureMachinePools) UpdateStatus(azureMachinePool *v1alpha3.AzureMachinePool) (result *v1alpha3.AzureMachinePool, err error) {
	result = &v1alpha3.AzureMachinePool{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("azuremachinepools").
		Name(azureMachinePool.Name).
		SubResource("status").
		Body(azureMachinePool).
		Do().
		Into(result)
	return
}

// Delete takes name of the azureMachinePool and deletes it. Returns an error if one occurs.
func (c *azureMachinePools) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("azuremachinepools").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *azureMachinePools) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("azuremachinepools").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched azureMachinePool.
func (c *azureMachinePools) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha3.AzureMachinePool, err error) {
	result = &v1alpha3.AzureMachinePool{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("azuremachinepools").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
