/*
Copyright 2020 Giant Swarm GmbH.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	v1alpha1 "github.com/giantswarm/apiextensions/pkg/apis/core/v1alpha1"
)

// FakeSparks implements SparkInterface
type FakeSparks struct {
	Fake *FakeCoreV1alpha1
	ns   string
}

var sparksResource = schema.GroupVersionResource{Group: "core.giantswarm.io", Version: "v1alpha1", Resource: "sparks"}

var sparksKind = schema.GroupVersionKind{Group: "core.giantswarm.io", Version: "v1alpha1", Kind: "Spark"}

// Get takes name of the spark, and returns the corresponding spark object, and an error if there is any.
func (c *FakeSparks) Get(name string, options v1.GetOptions) (result *v1alpha1.Spark, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sparksResource, c.ns, name), &v1alpha1.Spark{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Spark), err
}

// List takes label and field selectors, and returns the list of Sparks that match those selectors.
func (c *FakeSparks) List(opts v1.ListOptions) (result *v1alpha1.SparkList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sparksResource, sparksKind, c.ns, opts), &v1alpha1.SparkList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SparkList{ListMeta: obj.(*v1alpha1.SparkList).ListMeta}
	for _, item := range obj.(*v1alpha1.SparkList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sparks.
func (c *FakeSparks) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sparksResource, c.ns, opts))

}

// Create takes the representation of a spark and creates it.  Returns the server's representation of the spark, and an error, if there is any.
func (c *FakeSparks) Create(spark *v1alpha1.Spark) (result *v1alpha1.Spark, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sparksResource, c.ns, spark), &v1alpha1.Spark{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Spark), err
}

// Update takes the representation of a spark and updates it. Returns the server's representation of the spark, and an error, if there is any.
func (c *FakeSparks) Update(spark *v1alpha1.Spark) (result *v1alpha1.Spark, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sparksResource, c.ns, spark), &v1alpha1.Spark{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Spark), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSparks) UpdateStatus(spark *v1alpha1.Spark) (*v1alpha1.Spark, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(sparksResource, "status", c.ns, spark), &v1alpha1.Spark{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Spark), err
}

// Delete takes name of the spark and deletes it. Returns an error if one occurs.
func (c *FakeSparks) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(sparksResource, c.ns, name), &v1alpha1.Spark{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSparks) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sparksResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.SparkList{})
	return err
}

// Patch applies the patch and returns the patched spark.
func (c *FakeSparks) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Spark, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sparksResource, c.ns, name, pt, data, subresources...), &v1alpha1.Spark{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Spark), err
}
