/*
Copyright 2021 Giant Swarm GmbH.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	v1alpha2 "github.com/giantswarm/apiextensions/v3/pkg/apis/infrastructure/v1alpha2"
)

// FakeNetworkPools implements NetworkPoolInterface
type FakeNetworkPools struct {
	Fake *FakeInfrastructureV1alpha2
	ns   string
}

var networkpoolsResource = schema.GroupVersionResource{Group: "infrastructure.giantswarm.io", Version: "v1alpha2", Resource: "networkpools"}

var networkpoolsKind = schema.GroupVersionKind{Group: "infrastructure.giantswarm.io", Version: "v1alpha2", Kind: "NetworkPool"}

// Get takes name of the networkPool, and returns the corresponding networkPool object, and an error if there is any.
func (c *FakeNetworkPools) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.NetworkPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(networkpoolsResource, c.ns, name), &v1alpha2.NetworkPool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.NetworkPool), err
}

// List takes label and field selectors, and returns the list of NetworkPools that match those selectors.
func (c *FakeNetworkPools) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha2.NetworkPoolList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(networkpoolsResource, networkpoolsKind, c.ns, opts), &v1alpha2.NetworkPoolList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.NetworkPoolList{ListMeta: obj.(*v1alpha2.NetworkPoolList).ListMeta}
	for _, item := range obj.(*v1alpha2.NetworkPoolList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested networkPools.
func (c *FakeNetworkPools) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(networkpoolsResource, c.ns, opts))

}

// Create takes the representation of a networkPool and creates it.  Returns the server's representation of the networkPool, and an error, if there is any.
func (c *FakeNetworkPools) Create(ctx context.Context, networkPool *v1alpha2.NetworkPool, opts v1.CreateOptions) (result *v1alpha2.NetworkPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(networkpoolsResource, c.ns, networkPool), &v1alpha2.NetworkPool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.NetworkPool), err
}

// Update takes the representation of a networkPool and updates it. Returns the server's representation of the networkPool, and an error, if there is any.
func (c *FakeNetworkPools) Update(ctx context.Context, networkPool *v1alpha2.NetworkPool, opts v1.UpdateOptions) (result *v1alpha2.NetworkPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(networkpoolsResource, c.ns, networkPool), &v1alpha2.NetworkPool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.NetworkPool), err
}

// Delete takes name of the networkPool and deletes it. Returns an error if one occurs.
func (c *FakeNetworkPools) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(networkpoolsResource, c.ns, name), &v1alpha2.NetworkPool{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNetworkPools) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(networkpoolsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha2.NetworkPoolList{})
	return err
}

// Patch applies the patch and returns the patched networkPool.
func (c *FakeNetworkPools) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.NetworkPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(networkpoolsResource, c.ns, name, pt, data, subresources...), &v1alpha2.NetworkPool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.NetworkPool), err
}
