resources:
  - ../../../v1/release.giantswarm.io_releases.yaml
patchesJson6902:
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: releases.release.giantswarm.io
    path: patch.yaml
