apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: appcatalogs.application.giantswarm.io
spec:
  group: application.giantswarm.io
  names:
    kind: AppCatalog
    plural: appcatalogs
    singular: appcatalog
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: |
        An AppCatalog defines a collection of apps to install in one or several clusters.
      properties:
        spec:
          properties:
            config:
              description: |
                Configuration to be applied when apps from this catalog are deployed.
              properties:
                configMap:
                  description: |
                    References a ConfigMap containing catalog values that should be applied to
                    apps installed from this catalog.
                  properties:
                    name:
                      description: |
                        Name of the ConfigMap resource.
                      type: string
                    namespace:
                      description: |
                        Namespace holding the ConfigMap resource.
                      type: string
                  required:
                  - name
                  - namespace
                  type: object
                secret:
                  description: |
                    References a secret containing catalog values that should be applied to
                    apps installed from this catalog.
                  properties:
                    name:
                      description: |
                        Name of the Secret resource.
                      type: string
                    namespace:
                      description: |
                        Namespace holding the Secret resource.
                      type: string
                  required:
                  - name
                  - namespace
                  type: object
              type: object
            description:
              description: |
                Additional information regarding the purpose and other details of the catalog.
              type: string
            logoURL:
              description: |
                URL of a logo image file to be used when displaying this catalog.
              type: string
            storage:
              description: |
                References a map containing values that should be applied to this catalog.
              properties:
                URL:
                  description: |
                    URL to the app repository.
                  format: uri
                  type: string
                type:
                  description: |
                    Indicates which repository type would be used for this AppCatalog.
                    Example: 'helm'
                  type: string
              required:
              - type
              - URL
              type: object
            title:
              description: "User-friendly name of the catalog.    \n"
              type: string
          required:
          - title
          - description
          - storage
          type: object
  version: v1alpha1
