apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: appcatalogs.application.giantswarm.io
spec:
  group: application.giantswarm.io
  names:
    kind: AppCatalog
    plural: appcatalogs
    singular: appcatalog
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: |
        Defines a location where packaged applications are stored and shared,
        ready to be installed in a Kubernetes cluster.
      properties:
        spec:
          properties:
            config:
              description: "Defines the reference of a ConfigMap where is saved the
                default values that \nwill be applied to all applications contained
                in the catalog.\n"
              properties:
                configMap:
                  description: |
                    References a ConfigMap containing catalog values that should be applied to
                    apps installed from this catalog.
                  properties:
                    name:
                      description: |
                        Name of the ConfigMap resource.
                      type: string
                    namespace:
                      description: |
                        Namespace holding the ConfigMap resource.
                      type: string
                  required:
                  - name
                  - namespace
                  type: object
                secret:
                  description: |
                    Defines the reference of a Secret where is saved the default sensitive configuration
                    that will be applied to all applications contained in the catalog.
                  properties:
                    name:
                      description: |
                        Name of the Secret resource.
                      type: string
                    namespace:
                      description: |
                        Namespace holding the Secret resource.
                      type: string
                  required:
                  - name
                  - namespace
                  type: object
              type: object
            description:
              description: |
                Additional information regarding the purpose and other details of the catalog.
              type: string
            logoURL:
              description: |
                The logo URL pointing to the image file to be used when displaying this catalog.
              type: string
            storage:
              description: |
                Defines the type of storage supported by the catalog.
              properties:
                URL:
                  description: |
                    URL to the app repository.
                  format: uri
                  type: string
                type:
                  description: |
                    Determines the type of storage. Currently only 'helm' is available.
                    - Helm type storage use the known Helm Chart Repository format to store the chart
                      packages and expose some metadata in the file 'index.yaml' to manage the catalog.
                  type: string
              required:
              - type
              - URL
              type: object
            title:
              description: "User-friendly name of the catalog.    \n"
              type: string
          required:
          - title
          - description
          - storage
          type: object
      type: object
  version: v1alpha1
