apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: awsclusters.infrastructure.giantswarm.io
spec:
  group: infrastructure.giantswarm.io
  names:
    kind: AWSCluster
    plural: awsclusters
    singular: awscluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            cluster:
              properties:
                description:
                  maxLength: 100
                  type: string
                dns:
                  properties:
                    domain:
                      type: string
                    provider:
                      properties:
                        master:
                          properties:
                            availabilityZone:
                              type: string
                            instanceType:
                              type: string
                          type: object
                        region:
                          type: string
                      type: object
                  type: object
              type: object
          type: object
  version: v1alpha2
