apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: g8scontrolplanes.infrastructure.giantswarm.io
spec:
  conversion:
    strategy: None
  group: infrastructure.giantswarm.io
  names:
    kind: G8sControlPlane
    plural: g8scontrolplanes
    singular: g8scontrolplane
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: false
    storage: false
  - name: v1alpha2
    schema:
      openAPIV3Schema:
        description: |
          This resource represents an abstract control plane (Kubernetes master node and Etcd server)
          of a tenant cluster in a Giant Swarm installation. It is reconciled by cluster-operator.
          For implementation details it references a provider specific resource.
        properties:
          spec:
            properties:
              infrastructureRef:
                description: |
                  Reference to an [AWSControlPlane](https://docs.giantswarm.io/reference/cp-k8s-api/awscontrolplanes.infrastructure.giantswarm.io/)
                  resource defining provider specific details for the c
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  name:
                    type: string
                  namespace:
                    type: string
                type: object
              replicas:
                description: |
                  Number of master nodes and Etcd instances to set up.
                enum:
                - 1
                - 3
                type: integer
            type: object
        type: object
    served: true
    storage: true
