apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: Release.release.giantswarm.io
spec:
  group: release.giantswarm.io
  names:
    kind: Release
    plural: releases
    singular: release
  preserveUnknownFields: false
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              apps:
                items:
                  properties:
                    componentVersion:
                      pattern: ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-dev)?$
                      type: string
                    name:
                      minLength: 1
                      type: string
                    version:
                      pattern: ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-dev)?$
                      type: string
                  required:
                  - name
                  - version
                  type: object
                type: array
              components:
                items:
                  properties:
                    name:
                      minLength: 1
                      type: string
                    version:
                      pattern: ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-dev)?$
                      type: string
                  required:
                  - name
                  - version
                  type: object
                minItems: 1
                type: array
              state:
                pattern: ^(active|deprecated|wip)$
                type: string
              version:
                pattern: ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-dev)?$
                type: string
            required:
            - components
            - apps
            - state
            - version
            type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
