/*
Copyright 2019 Giant Swarm GmbH.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/giantswarm/apiextensions/pkg/apis/example/v1alpha1"
	scheme "github.com/giantswarm/apiextensions/pkg/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GitHubSearchIndexesGetter has a method to return a GitHubSearchIndexInterface.
// A group's client should implement this interface.
type GitHubSearchIndexesGetter interface {
	GitHubSearchIndexes(namespace string) GitHubSearchIndexInterface
}

// GitHubSearchIndexInterface has methods to work with GitHubSearchIndex resources.
type GitHubSearchIndexInterface interface {
	Create(*v1alpha1.GitHubSearchIndex) (*v1alpha1.GitHubSearchIndex, error)
	Update(*v1alpha1.GitHubSearchIndex) (*v1alpha1.GitHubSearchIndex, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.GitHubSearchIndex, error)
	List(opts v1.ListOptions) (*v1alpha1.GitHubSearchIndexList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.GitHubSearchIndex, err error)
	GitHubSearchIndexExpansion
}

// gitHubSearchIndexes implements GitHubSearchIndexInterface
type gitHubSearchIndexes struct {
	client rest.Interface
	ns     string
}

// newGitHubSearchIndexes returns a GitHubSearchIndexes
func newGitHubSearchIndexes(c *ExampleV1alpha1Client, namespace string) *gitHubSearchIndexes {
	return &gitHubSearchIndexes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the gitHubSearchIndex, and returns the corresponding gitHubSearchIndex object, and an error if there is any.
func (c *gitHubSearchIndexes) Get(name string, options v1.GetOptions) (result *v1alpha1.GitHubSearchIndex, err error) {
	result = &v1alpha1.GitHubSearchIndex{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("githubsearchindexes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GitHubSearchIndexes that match those selectors.
func (c *gitHubSearchIndexes) List(opts v1.ListOptions) (result *v1alpha1.GitHubSearchIndexList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.GitHubSearchIndexList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("githubsearchindexes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested gitHubSearchIndexes.
func (c *gitHubSearchIndexes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("githubsearchindexes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a gitHubSearchIndex and creates it.  Returns the server's representation of the gitHubSearchIndex, and an error, if there is any.
func (c *gitHubSearchIndexes) Create(gitHubSearchIndex *v1alpha1.GitHubSearchIndex) (result *v1alpha1.GitHubSearchIndex, err error) {
	result = &v1alpha1.GitHubSearchIndex{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("githubsearchindexes").
		Body(gitHubSearchIndex).
		Do().
		Into(result)
	return
}

// Update takes the representation of a gitHubSearchIndex and updates it. Returns the server's representation of the gitHubSearchIndex, and an error, if there is any.
func (c *gitHubSearchIndexes) Update(gitHubSearchIndex *v1alpha1.GitHubSearchIndex) (result *v1alpha1.GitHubSearchIndex, err error) {
	result = &v1alpha1.GitHubSearchIndex{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("githubsearchindexes").
		Name(gitHubSearchIndex.Name).
		Body(gitHubSearchIndex).
		Do().
		Into(result)
	return
}

// Delete takes name of the gitHubSearchIndex and deletes it. Returns an error if one occurs.
func (c *gitHubSearchIndexes) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("githubsearchindexes").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *gitHubSearchIndexes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("githubsearchindexes").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched gitHubSearchIndex.
func (c *gitHubSearchIndexes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.GitHubSearchIndex, err error) {
	result = &v1alpha1.GitHubSearchIndex{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("githubsearchindexes").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
