/*
Copyright 2019 Giant Swarm GmbH.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/giantswarm/apiextensions/pkg/apis/example/v1alpha1"
	scheme "github.com/giantswarm/apiextensions/pkg/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SearchIndexesGetter has a method to return a SearchIndexInterface.
// A group's client should implement this interface.
type SearchIndexesGetter interface {
	SearchIndexes(namespace string) SearchIndexInterface
}

// SearchIndexInterface has methods to work with SearchIndex resources.
type SearchIndexInterface interface {
	Create(*v1alpha1.SearchIndex) (*v1alpha1.SearchIndex, error)
	Update(*v1alpha1.SearchIndex) (*v1alpha1.SearchIndex, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.SearchIndex, error)
	List(opts v1.ListOptions) (*v1alpha1.SearchIndexList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SearchIndex, err error)
	SearchIndexExpansion
}

// searchIndexes implements SearchIndexInterface
type searchIndexes struct {
	client rest.Interface
	ns     string
}

// newSearchIndexes returns a SearchIndexes
func newSearchIndexes(c *ExampleV1alpha1Client, namespace string) *searchIndexes {
	return &searchIndexes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the searchIndex, and returns the corresponding searchIndex object, and an error if there is any.
func (c *searchIndexes) Get(name string, options v1.GetOptions) (result *v1alpha1.SearchIndex, err error) {
	result = &v1alpha1.SearchIndex{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("searchindexes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SearchIndexes that match those selectors.
func (c *searchIndexes) List(opts v1.ListOptions) (result *v1alpha1.SearchIndexList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SearchIndexList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("searchindexes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested searchIndexes.
func (c *searchIndexes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("searchindexes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a searchIndex and creates it.  Returns the server's representation of the searchIndex, and an error, if there is any.
func (c *searchIndexes) Create(searchIndex *v1alpha1.SearchIndex) (result *v1alpha1.SearchIndex, err error) {
	result = &v1alpha1.SearchIndex{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("searchindexes").
		Body(searchIndex).
		Do().
		Into(result)
	return
}

// Update takes the representation of a searchIndex and updates it. Returns the server's representation of the searchIndex, and an error, if there is any.
func (c *searchIndexes) Update(searchIndex *v1alpha1.SearchIndex) (result *v1alpha1.SearchIndex, err error) {
	result = &v1alpha1.SearchIndex{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("searchindexes").
		Name(searchIndex.Name).
		Body(searchIndex).
		Do().
		Into(result)
	return
}

// Delete takes name of the searchIndex and deletes it. Returns an error if one occurs.
func (c *searchIndexes) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("searchindexes").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *searchIndexes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("searchindexes").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched searchIndex.
func (c *searchIndexes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SearchIndex, err error) {
	result = &v1alpha1.SearchIndex{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("searchindexes").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
