// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	net "net"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWS) DeepCopyInto(out *AWS) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWS.
func (in *AWS) DeepCopy() *AWS {
	if in == nil {
		return nil
	}
	out := new(AWS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWS) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSList) DeepCopyInto(out *AWSList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AWS, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSList.
func (in *AWSList) DeepCopy() *AWSList {
	if in == nil {
		return nil
	}
	out := new(AWSList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSpec) DeepCopyInto(out *AWSSpec) {
	*out = *in
	in.Cluster.DeepCopyInto(&out.Cluster)
	in.AWS.DeepCopyInto(&out.AWS)
	out.VersionBundle = in.VersionBundle.DeepCopy()
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSpec.
func (in *AWSSpec) DeepCopy() *AWSSpec {
	if in == nil {
		return nil
	}
	out := new(AWSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSpecAWS) DeepCopyInto(out *AWSSpecAWS) {
	*out = *in
	out.API = in.API
	out.Etcd = in.Etcd
	out.Ingress = in.Ingress
	if in.Masters != nil {
		in, out := &in.Masters, &out.Masters
		*out = make([]AWSSpecAWSNode, len(*in))
		copy(*out, *in)
	}
	in.VPC.DeepCopyInto(&out.VPC)
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = make([]AWSSpecAWSNode, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSpecAWS.
func (in *AWSSpecAWS) DeepCopy() *AWSSpecAWS {
	if in == nil {
		return nil
	}
	out := new(AWSSpecAWS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSpecAWSAPI) DeepCopyInto(out *AWSSpecAWSAPI) {
	*out = *in
	out.ELB = in.ELB
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSpecAWSAPI.
func (in *AWSSpecAWSAPI) DeepCopy() *AWSSpecAWSAPI {
	if in == nil {
		return nil
	}
	out := new(AWSSpecAWSAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSpecAWSAPIELB) DeepCopyInto(out *AWSSpecAWSAPIELB) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSpecAWSAPIELB.
func (in *AWSSpecAWSAPIELB) DeepCopy() *AWSSpecAWSAPIELB {
	if in == nil {
		return nil
	}
	out := new(AWSSpecAWSAPIELB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSpecAWSEtcd) DeepCopyInto(out *AWSSpecAWSEtcd) {
	*out = *in
	out.ELB = in.ELB
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSpecAWSEtcd.
func (in *AWSSpecAWSEtcd) DeepCopy() *AWSSpecAWSEtcd {
	if in == nil {
		return nil
	}
	out := new(AWSSpecAWSEtcd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSpecAWSEtcdELB) DeepCopyInto(out *AWSSpecAWSEtcdELB) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSpecAWSEtcdELB.
func (in *AWSSpecAWSEtcdELB) DeepCopy() *AWSSpecAWSEtcdELB {
	if in == nil {
		return nil
	}
	out := new(AWSSpecAWSEtcdELB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSpecAWSIngress) DeepCopyInto(out *AWSSpecAWSIngress) {
	*out = *in
	out.ELB = in.ELB
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSpecAWSIngress.
func (in *AWSSpecAWSIngress) DeepCopy() *AWSSpecAWSIngress {
	if in == nil {
		return nil
	}
	out := new(AWSSpecAWSIngress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSpecAWSIngressELB) DeepCopyInto(out *AWSSpecAWSIngressELB) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSpecAWSIngressELB.
func (in *AWSSpecAWSIngressELB) DeepCopy() *AWSSpecAWSIngressELB {
	if in == nil {
		return nil
	}
	out := new(AWSSpecAWSIngressELB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSpecAWSNode) DeepCopyInto(out *AWSSpecAWSNode) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSpecAWSNode.
func (in *AWSSpecAWSNode) DeepCopy() *AWSSpecAWSNode {
	if in == nil {
		return nil
	}
	out := new(AWSSpecAWSNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSpecAWSVPC) DeepCopyInto(out *AWSSpecAWSVPC) {
	*out = *in
	if in.RouteTableNames != nil {
		in, out := &in.RouteTableNames, &out.RouteTableNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSpecAWSVPC.
func (in *AWSSpecAWSVPC) DeepCopy() *AWSSpecAWSVPC {
	if in == nil {
		return nil
	}
	out := new(AWSSpecAWSVPC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSpecCluster) DeepCopyInto(out *AWSSpecCluster) {
	*out = *in
	out.Calico = in.Calico
	out.Customer = in.Customer
	out.Docker = in.Docker
	out.Etcd = in.Etcd
	out.Kubernetes = in.Kubernetes.DeepCopy()
	if in.Masters != nil {
		in, out := &in.Masters, &out.Masters
		*out = make([]AWSSpecClusterNode, len(*in))
		copy(*out, *in)
	}
	out.Vault = in.Vault
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = make([]AWSSpecClusterNode, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSpecCluster.
func (in *AWSSpecCluster) DeepCopy() *AWSSpecCluster {
	if in == nil {
		return nil
	}
	out := new(AWSSpecCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSpecClusterCalico) DeepCopyInto(out *AWSSpecClusterCalico) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSpecClusterCalico.
func (in *AWSSpecClusterCalico) DeepCopy() *AWSSpecClusterCalico {
	if in == nil {
		return nil
	}
	out := new(AWSSpecClusterCalico)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSpecClusterCustomer) DeepCopyInto(out *AWSSpecClusterCustomer) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSpecClusterCustomer.
func (in *AWSSpecClusterCustomer) DeepCopy() *AWSSpecClusterCustomer {
	if in == nil {
		return nil
	}
	out := new(AWSSpecClusterCustomer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSpecClusterDocker) DeepCopyInto(out *AWSSpecClusterDocker) {
	*out = *in
	out.Daemon = in.Daemon
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSpecClusterDocker.
func (in *AWSSpecClusterDocker) DeepCopy() *AWSSpecClusterDocker {
	if in == nil {
		return nil
	}
	out := new(AWSSpecClusterDocker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSpecClusterDockerDaemon) DeepCopyInto(out *AWSSpecClusterDockerDaemon) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSpecClusterDockerDaemon.
func (in *AWSSpecClusterDockerDaemon) DeepCopy() *AWSSpecClusterDockerDaemon {
	if in == nil {
		return nil
	}
	out := new(AWSSpecClusterDockerDaemon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSpecClusterEtcd) DeepCopyInto(out *AWSSpecClusterEtcd) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSpecClusterEtcd.
func (in *AWSSpecClusterEtcd) DeepCopy() *AWSSpecClusterEtcd {
	if in == nil {
		return nil
	}
	out := new(AWSSpecClusterEtcd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSpecClusterKubernetes) DeepCopyInto(out *AWSSpecClusterKubernetes) {
	*out = *in
	in.API.DeepCopyInto(&out.API)
	in.DNS.DeepCopyInto(&out.DNS)
	out.Hyperkube = in.Hyperkube
	out.IngressController = in.IngressController
	out.Kubelet = in.Kubelet
	out.NetworkSetup = in.NetworkSetup
	in.SSH.DeepCopyInto(&out.SSH)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSpecClusterKubernetes.
func (in *AWSSpecClusterKubernetes) DeepCopy() *AWSSpecClusterKubernetes {
	if in == nil {
		return nil
	}
	out := new(AWSSpecClusterKubernetes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSpecClusterKubernetesAPI) DeepCopyInto(out *AWSSpecClusterKubernetesAPI) {
	*out = *in
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = make(net.IP, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSpecClusterKubernetesAPI.
func (in *AWSSpecClusterKubernetesAPI) DeepCopy() *AWSSpecClusterKubernetesAPI {
	if in == nil {
		return nil
	}
	out := new(AWSSpecClusterKubernetesAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSpecClusterKubernetesDNS) DeepCopyInto(out *AWSSpecClusterKubernetesDNS) {
	*out = *in
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = make(net.IP, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSpecClusterKubernetesDNS.
func (in *AWSSpecClusterKubernetesDNS) DeepCopy() *AWSSpecClusterKubernetesDNS {
	if in == nil {
		return nil
	}
	out := new(AWSSpecClusterKubernetesDNS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSpecClusterKubernetesHyperkube) DeepCopyInto(out *AWSSpecClusterKubernetesHyperkube) {
	*out = *in
	out.Docker = in.Docker
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSpecClusterKubernetesHyperkube.
func (in *AWSSpecClusterKubernetesHyperkube) DeepCopy() *AWSSpecClusterKubernetesHyperkube {
	if in == nil {
		return nil
	}
	out := new(AWSSpecClusterKubernetesHyperkube)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSpecClusterKubernetesHyperkubeDocker) DeepCopyInto(out *AWSSpecClusterKubernetesHyperkubeDocker) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSpecClusterKubernetesHyperkubeDocker.
func (in *AWSSpecClusterKubernetesHyperkubeDocker) DeepCopy() *AWSSpecClusterKubernetesHyperkubeDocker {
	if in == nil {
		return nil
	}
	out := new(AWSSpecClusterKubernetesHyperkubeDocker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSpecClusterKubernetesIngressController) DeepCopyInto(out *AWSSpecClusterKubernetesIngressController) {
	*out = *in
	out.Docker = in.Docker
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSpecClusterKubernetesIngressController.
func (in *AWSSpecClusterKubernetesIngressController) DeepCopy() *AWSSpecClusterKubernetesIngressController {
	if in == nil {
		return nil
	}
	out := new(AWSSpecClusterKubernetesIngressController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSpecClusterKubernetesIngressControllerDocker) DeepCopyInto(out *AWSSpecClusterKubernetesIngressControllerDocker) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSpecClusterKubernetesIngressControllerDocker.
func (in *AWSSpecClusterKubernetesIngressControllerDocker) DeepCopy() *AWSSpecClusterKubernetesIngressControllerDocker {
	if in == nil {
		return nil
	}
	out := new(AWSSpecClusterKubernetesIngressControllerDocker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSpecClusterKubernetesKubelet) DeepCopyInto(out *AWSSpecClusterKubernetesKubelet) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSpecClusterKubernetesKubelet.
func (in *AWSSpecClusterKubernetesKubelet) DeepCopy() *AWSSpecClusterKubernetesKubelet {
	if in == nil {
		return nil
	}
	out := new(AWSSpecClusterKubernetesKubelet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSpecClusterKubernetesNetworkSetup) DeepCopyInto(out *AWSSpecClusterKubernetesNetworkSetup) {
	*out = *in
	out.Docker = in.Docker
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSpecClusterKubernetesNetworkSetup.
func (in *AWSSpecClusterKubernetesNetworkSetup) DeepCopy() *AWSSpecClusterKubernetesNetworkSetup {
	if in == nil {
		return nil
	}
	out := new(AWSSpecClusterKubernetesNetworkSetup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSpecClusterKubernetesNetworkSetupDocker) DeepCopyInto(out *AWSSpecClusterKubernetesNetworkSetupDocker) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSpecClusterKubernetesNetworkSetupDocker.
func (in *AWSSpecClusterKubernetesNetworkSetupDocker) DeepCopy() *AWSSpecClusterKubernetesNetworkSetupDocker {
	if in == nil {
		return nil
	}
	out := new(AWSSpecClusterKubernetesNetworkSetupDocker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSpecClusterKubernetesSSH) DeepCopyInto(out *AWSSpecClusterKubernetesSSH) {
	*out = *in
	if in.UserList != nil {
		in, out := &in.UserList, &out.UserList
		*out = make([]AWSSpecClusterKubernetesSSHUser, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSpecClusterKubernetesSSH.
func (in *AWSSpecClusterKubernetesSSH) DeepCopy() *AWSSpecClusterKubernetesSSH {
	if in == nil {
		return nil
	}
	out := new(AWSSpecClusterKubernetesSSH)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSpecClusterKubernetesSSHUser) DeepCopyInto(out *AWSSpecClusterKubernetesSSHUser) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSpecClusterKubernetesSSHUser.
func (in *AWSSpecClusterKubernetesSSHUser) DeepCopy() *AWSSpecClusterKubernetesSSHUser {
	if in == nil {
		return nil
	}
	out := new(AWSSpecClusterKubernetesSSHUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSpecClusterNode) DeepCopyInto(out *AWSSpecClusterNode) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSpecClusterNode.
func (in *AWSSpecClusterNode) DeepCopy() *AWSSpecClusterNode {
	if in == nil {
		return nil
	}
	out := new(AWSSpecClusterNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSpecClusterVault) DeepCopyInto(out *AWSSpecClusterVault) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSpecClusterVault.
func (in *AWSSpecClusterVault) DeepCopy() *AWSSpecClusterVault {
	if in == nil {
		return nil
	}
	out := new(AWSSpecClusterVault)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Azure) DeepCopyInto(out *Azure) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Azure.
func (in *Azure) DeepCopy() *Azure {
	if in == nil {
		return nil
	}
	out := new(Azure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Azure) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureDNSZones) DeepCopyInto(out *AzureDNSZones) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureDNSZones.
func (in *AzureDNSZones) DeepCopy() *AzureDNSZones {
	if in == nil {
		return nil
	}
	out := new(AzureDNSZones)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureKeyVault) DeepCopyInto(out *AzureKeyVault) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureKeyVault.
func (in *AzureKeyVault) DeepCopy() *AzureKeyVault {
	if in == nil {
		return nil
	}
	out := new(AzureKeyVault)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureList) DeepCopyInto(out *AzureList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Azure, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureList.
func (in *AzureList) DeepCopy() *AzureList {
	if in == nil {
		return nil
	}
	out := new(AzureList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureLoadBalancer) DeepCopyInto(out *AzureLoadBalancer) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureLoadBalancer.
func (in *AzureLoadBalancer) DeepCopy() *AzureLoadBalancer {
	if in == nil {
		return nil
	}
	out := new(AzureLoadBalancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureNode) DeepCopyInto(out *AzureNode) {
	*out = *in
	out.OSImage = in.OSImage
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureNode.
func (in *AzureNode) DeepCopy() *AzureNode {
	if in == nil {
		return nil
	}
	out := new(AzureNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureOSImage) DeepCopyInto(out *AzureOSImage) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureOSImage.
func (in *AzureOSImage) DeepCopy() *AzureOSImage {
	if in == nil {
		return nil
	}
	out := new(AzureOSImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureResourceGroup) DeepCopyInto(out *AzureResourceGroup) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureResourceGroup.
func (in *AzureResourceGroup) DeepCopy() *AzureResourceGroup {
	if in == nil {
		return nil
	}
	out := new(AzureResourceGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureSpec) DeepCopyInto(out *AzureSpec) {
	*out = *in
	out.KeyVault = in.KeyVault
	out.ResourceGroup = in.ResourceGroup
	out.Storage = in.Storage
	out.VirtualNetwork = in.VirtualNetwork
	if in.Masters != nil {
		in, out := &in.Masters, &out.Masters
		*out = make([]AzureNode, len(*in))
		copy(*out, *in)
	}
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = make([]AzureNode, len(*in))
		copy(*out, *in)
	}
	out.DNSZones = in.DNSZones
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureSpec.
func (in *AzureSpec) DeepCopy() *AzureSpec {
	if in == nil {
		return nil
	}
	out := new(AzureSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureStorage) DeepCopyInto(out *AzureStorage) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureStorage.
func (in *AzureStorage) DeepCopy() *AzureStorage {
	if in == nil {
		return nil
	}
	out := new(AzureStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVirtualNetwork) DeepCopyInto(out *AzureVirtualNetwork) {
	*out = *in
	out.LoadBalancer = in.LoadBalancer
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVirtualNetwork.
func (in *AzureVirtualNetwork) DeepCopy() *AzureVirtualNetwork {
	if in == nil {
		return nil
	}
	out := new(AzureVirtualNetwork)
	in.DeepCopyInto(out)
	return out
}
