// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	net "net"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfig) DeepCopyInto(out *AWSConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfig.
func (in *AWSConfig) DeepCopy() *AWSConfig {
	if in == nil {
		return nil
	}
	out := new(AWSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigList) DeepCopyInto(out *AWSConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AWSConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigList.
func (in *AWSConfigList) DeepCopy() *AWSConfigList {
	if in == nil {
		return nil
	}
	out := new(AWSConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigSpec) DeepCopyInto(out *AWSConfigSpec) {
	*out = *in
	in.Cluster.DeepCopyInto(&out.Cluster)
	in.AWS.DeepCopyInto(&out.AWS)
	out.VersionBundle = in.VersionBundle
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigSpec.
func (in *AWSConfigSpec) DeepCopy() *AWSConfigSpec {
	if in == nil {
		return nil
	}
	out := new(AWSConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigSpecAWS) DeepCopyInto(out *AWSConfigSpecAWS) {
	*out = *in
	out.API = in.API
	out.Etcd = in.Etcd
	out.Ingress = in.Ingress
	if in.Masters != nil {
		in, out := &in.Masters, &out.Masters
		*out = make([]AWSConfigSpecAWSNode, len(*in))
		copy(*out, *in)
	}
	in.VPC.DeepCopyInto(&out.VPC)
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = make([]AWSConfigSpecAWSNode, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigSpecAWS.
func (in *AWSConfigSpecAWS) DeepCopy() *AWSConfigSpecAWS {
	if in == nil {
		return nil
	}
	out := new(AWSConfigSpecAWS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigSpecAWSAPI) DeepCopyInto(out *AWSConfigSpecAWSAPI) {
	*out = *in
	out.ELB = in.ELB
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigSpecAWSAPI.
func (in *AWSConfigSpecAWSAPI) DeepCopy() *AWSConfigSpecAWSAPI {
	if in == nil {
		return nil
	}
	out := new(AWSConfigSpecAWSAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigSpecAWSAPIELB) DeepCopyInto(out *AWSConfigSpecAWSAPIELB) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigSpecAWSAPIELB.
func (in *AWSConfigSpecAWSAPIELB) DeepCopy() *AWSConfigSpecAWSAPIELB {
	if in == nil {
		return nil
	}
	out := new(AWSConfigSpecAWSAPIELB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigSpecAWSEtcd) DeepCopyInto(out *AWSConfigSpecAWSEtcd) {
	*out = *in
	out.ELB = in.ELB
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigSpecAWSEtcd.
func (in *AWSConfigSpecAWSEtcd) DeepCopy() *AWSConfigSpecAWSEtcd {
	if in == nil {
		return nil
	}
	out := new(AWSConfigSpecAWSEtcd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigSpecAWSEtcdELB) DeepCopyInto(out *AWSConfigSpecAWSEtcdELB) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigSpecAWSEtcdELB.
func (in *AWSConfigSpecAWSEtcdELB) DeepCopy() *AWSConfigSpecAWSEtcdELB {
	if in == nil {
		return nil
	}
	out := new(AWSConfigSpecAWSEtcdELB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigSpecAWSIngress) DeepCopyInto(out *AWSConfigSpecAWSIngress) {
	*out = *in
	out.ELB = in.ELB
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigSpecAWSIngress.
func (in *AWSConfigSpecAWSIngress) DeepCopy() *AWSConfigSpecAWSIngress {
	if in == nil {
		return nil
	}
	out := new(AWSConfigSpecAWSIngress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigSpecAWSIngressELB) DeepCopyInto(out *AWSConfigSpecAWSIngressELB) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigSpecAWSIngressELB.
func (in *AWSConfigSpecAWSIngressELB) DeepCopy() *AWSConfigSpecAWSIngressELB {
	if in == nil {
		return nil
	}
	out := new(AWSConfigSpecAWSIngressELB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigSpecAWSNode) DeepCopyInto(out *AWSConfigSpecAWSNode) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigSpecAWSNode.
func (in *AWSConfigSpecAWSNode) DeepCopy() *AWSConfigSpecAWSNode {
	if in == nil {
		return nil
	}
	out := new(AWSConfigSpecAWSNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigSpecAWSVPC) DeepCopyInto(out *AWSConfigSpecAWSVPC) {
	*out = *in
	if in.RouteTableNames != nil {
		in, out := &in.RouteTableNames, &out.RouteTableNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigSpecAWSVPC.
func (in *AWSConfigSpecAWSVPC) DeepCopy() *AWSConfigSpecAWSVPC {
	if in == nil {
		return nil
	}
	out := new(AWSConfigSpecAWSVPC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigSpecCluster) DeepCopyInto(out *AWSConfigSpecCluster) {
	*out = *in
	out.Calico = in.Calico
	out.Customer = in.Customer
	out.Docker = in.Docker
	out.Etcd = in.Etcd
	in.Kubernetes.DeepCopyInto(&out.Kubernetes)
	if in.Masters != nil {
		in, out := &in.Masters, &out.Masters
		*out = make([]AWSConfigSpecClusterNode, len(*in))
		copy(*out, *in)
	}
	out.Vault = in.Vault
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = make([]AWSConfigSpecClusterNode, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigSpecCluster.
func (in *AWSConfigSpecCluster) DeepCopy() *AWSConfigSpecCluster {
	if in == nil {
		return nil
	}
	out := new(AWSConfigSpecCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigSpecClusterCalico) DeepCopyInto(out *AWSConfigSpecClusterCalico) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigSpecClusterCalico.
func (in *AWSConfigSpecClusterCalico) DeepCopy() *AWSConfigSpecClusterCalico {
	if in == nil {
		return nil
	}
	out := new(AWSConfigSpecClusterCalico)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigSpecClusterCustomer) DeepCopyInto(out *AWSConfigSpecClusterCustomer) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigSpecClusterCustomer.
func (in *AWSConfigSpecClusterCustomer) DeepCopy() *AWSConfigSpecClusterCustomer {
	if in == nil {
		return nil
	}
	out := new(AWSConfigSpecClusterCustomer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigSpecClusterDocker) DeepCopyInto(out *AWSConfigSpecClusterDocker) {
	*out = *in
	out.Daemon = in.Daemon
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigSpecClusterDocker.
func (in *AWSConfigSpecClusterDocker) DeepCopy() *AWSConfigSpecClusterDocker {
	if in == nil {
		return nil
	}
	out := new(AWSConfigSpecClusterDocker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigSpecClusterDockerDaemon) DeepCopyInto(out *AWSConfigSpecClusterDockerDaemon) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigSpecClusterDockerDaemon.
func (in *AWSConfigSpecClusterDockerDaemon) DeepCopy() *AWSConfigSpecClusterDockerDaemon {
	if in == nil {
		return nil
	}
	out := new(AWSConfigSpecClusterDockerDaemon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigSpecClusterEtcd) DeepCopyInto(out *AWSConfigSpecClusterEtcd) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigSpecClusterEtcd.
func (in *AWSConfigSpecClusterEtcd) DeepCopy() *AWSConfigSpecClusterEtcd {
	if in == nil {
		return nil
	}
	out := new(AWSConfigSpecClusterEtcd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigSpecClusterKubernetes) DeepCopyInto(out *AWSConfigSpecClusterKubernetes) {
	*out = *in
	in.API.DeepCopyInto(&out.API)
	in.DNS.DeepCopyInto(&out.DNS)
	out.Hyperkube = in.Hyperkube
	out.IngressController = in.IngressController
	out.Kubelet = in.Kubelet
	out.NetworkSetup = in.NetworkSetup
	in.SSH.DeepCopyInto(&out.SSH)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigSpecClusterKubernetes.
func (in *AWSConfigSpecClusterKubernetes) DeepCopy() *AWSConfigSpecClusterKubernetes {
	if in == nil {
		return nil
	}
	out := new(AWSConfigSpecClusterKubernetes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigSpecClusterKubernetesAPI) DeepCopyInto(out *AWSConfigSpecClusterKubernetesAPI) {
	*out = *in
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = make(net.IP, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigSpecClusterKubernetesAPI.
func (in *AWSConfigSpecClusterKubernetesAPI) DeepCopy() *AWSConfigSpecClusterKubernetesAPI {
	if in == nil {
		return nil
	}
	out := new(AWSConfigSpecClusterKubernetesAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigSpecClusterKubernetesDNS) DeepCopyInto(out *AWSConfigSpecClusterKubernetesDNS) {
	*out = *in
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = make(net.IP, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigSpecClusterKubernetesDNS.
func (in *AWSConfigSpecClusterKubernetesDNS) DeepCopy() *AWSConfigSpecClusterKubernetesDNS {
	if in == nil {
		return nil
	}
	out := new(AWSConfigSpecClusterKubernetesDNS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigSpecClusterKubernetesHyperkube) DeepCopyInto(out *AWSConfigSpecClusterKubernetesHyperkube) {
	*out = *in
	out.Docker = in.Docker
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigSpecClusterKubernetesHyperkube.
func (in *AWSConfigSpecClusterKubernetesHyperkube) DeepCopy() *AWSConfigSpecClusterKubernetesHyperkube {
	if in == nil {
		return nil
	}
	out := new(AWSConfigSpecClusterKubernetesHyperkube)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigSpecClusterKubernetesHyperkubeDocker) DeepCopyInto(out *AWSConfigSpecClusterKubernetesHyperkubeDocker) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigSpecClusterKubernetesHyperkubeDocker.
func (in *AWSConfigSpecClusterKubernetesHyperkubeDocker) DeepCopy() *AWSConfigSpecClusterKubernetesHyperkubeDocker {
	if in == nil {
		return nil
	}
	out := new(AWSConfigSpecClusterKubernetesHyperkubeDocker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigSpecClusterKubernetesIngressController) DeepCopyInto(out *AWSConfigSpecClusterKubernetesIngressController) {
	*out = *in
	out.Docker = in.Docker
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigSpecClusterKubernetesIngressController.
func (in *AWSConfigSpecClusterKubernetesIngressController) DeepCopy() *AWSConfigSpecClusterKubernetesIngressController {
	if in == nil {
		return nil
	}
	out := new(AWSConfigSpecClusterKubernetesIngressController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigSpecClusterKubernetesIngressControllerDocker) DeepCopyInto(out *AWSConfigSpecClusterKubernetesIngressControllerDocker) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigSpecClusterKubernetesIngressControllerDocker.
func (in *AWSConfigSpecClusterKubernetesIngressControllerDocker) DeepCopy() *AWSConfigSpecClusterKubernetesIngressControllerDocker {
	if in == nil {
		return nil
	}
	out := new(AWSConfigSpecClusterKubernetesIngressControllerDocker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigSpecClusterKubernetesKubelet) DeepCopyInto(out *AWSConfigSpecClusterKubernetesKubelet) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigSpecClusterKubernetesKubelet.
func (in *AWSConfigSpecClusterKubernetesKubelet) DeepCopy() *AWSConfigSpecClusterKubernetesKubelet {
	if in == nil {
		return nil
	}
	out := new(AWSConfigSpecClusterKubernetesKubelet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigSpecClusterKubernetesNetworkSetup) DeepCopyInto(out *AWSConfigSpecClusterKubernetesNetworkSetup) {
	*out = *in
	out.Docker = in.Docker
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigSpecClusterKubernetesNetworkSetup.
func (in *AWSConfigSpecClusterKubernetesNetworkSetup) DeepCopy() *AWSConfigSpecClusterKubernetesNetworkSetup {
	if in == nil {
		return nil
	}
	out := new(AWSConfigSpecClusterKubernetesNetworkSetup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigSpecClusterKubernetesNetworkSetupDocker) DeepCopyInto(out *AWSConfigSpecClusterKubernetesNetworkSetupDocker) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigSpecClusterKubernetesNetworkSetupDocker.
func (in *AWSConfigSpecClusterKubernetesNetworkSetupDocker) DeepCopy() *AWSConfigSpecClusterKubernetesNetworkSetupDocker {
	if in == nil {
		return nil
	}
	out := new(AWSConfigSpecClusterKubernetesNetworkSetupDocker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigSpecClusterKubernetesSSH) DeepCopyInto(out *AWSConfigSpecClusterKubernetesSSH) {
	*out = *in
	if in.UserList != nil {
		in, out := &in.UserList, &out.UserList
		*out = make([]AWSConfigSpecClusterKubernetesSSHUser, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigSpecClusterKubernetesSSH.
func (in *AWSConfigSpecClusterKubernetesSSH) DeepCopy() *AWSConfigSpecClusterKubernetesSSH {
	if in == nil {
		return nil
	}
	out := new(AWSConfigSpecClusterKubernetesSSH)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigSpecClusterKubernetesSSHUser) DeepCopyInto(out *AWSConfigSpecClusterKubernetesSSHUser) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigSpecClusterKubernetesSSHUser.
func (in *AWSConfigSpecClusterKubernetesSSHUser) DeepCopy() *AWSConfigSpecClusterKubernetesSSHUser {
	if in == nil {
		return nil
	}
	out := new(AWSConfigSpecClusterKubernetesSSHUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigSpecClusterNode) DeepCopyInto(out *AWSConfigSpecClusterNode) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigSpecClusterNode.
func (in *AWSConfigSpecClusterNode) DeepCopy() *AWSConfigSpecClusterNode {
	if in == nil {
		return nil
	}
	out := new(AWSConfigSpecClusterNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigSpecClusterVault) DeepCopyInto(out *AWSConfigSpecClusterVault) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigSpecClusterVault.
func (in *AWSConfigSpecClusterVault) DeepCopy() *AWSConfigSpecClusterVault {
	if in == nil {
		return nil
	}
	out := new(AWSConfigSpecClusterVault)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigSpecVersionBundle) DeepCopyInto(out *AWSConfigSpecVersionBundle) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigSpecVersionBundle.
func (in *AWSConfigSpecVersionBundle) DeepCopy() *AWSConfigSpecVersionBundle {
	if in == nil {
		return nil
	}
	out := new(AWSConfigSpecVersionBundle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureConfig) DeepCopyInto(out *AzureConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureConfig.
func (in *AzureConfig) DeepCopy() *AzureConfig {
	if in == nil {
		return nil
	}
	out := new(AzureConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureConfigDNSZones) DeepCopyInto(out *AzureConfigDNSZones) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureConfigDNSZones.
func (in *AzureConfigDNSZones) DeepCopy() *AzureConfigDNSZones {
	if in == nil {
		return nil
	}
	out := new(AzureConfigDNSZones)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureConfigKeyVault) DeepCopyInto(out *AzureConfigKeyVault) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureConfigKeyVault.
func (in *AzureConfigKeyVault) DeepCopy() *AzureConfigKeyVault {
	if in == nil {
		return nil
	}
	out := new(AzureConfigKeyVault)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureConfigList) DeepCopyInto(out *AzureConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureConfigList.
func (in *AzureConfigList) DeepCopy() *AzureConfigList {
	if in == nil {
		return nil
	}
	out := new(AzureConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureConfigLoadBalancer) DeepCopyInto(out *AzureConfigLoadBalancer) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureConfigLoadBalancer.
func (in *AzureConfigLoadBalancer) DeepCopy() *AzureConfigLoadBalancer {
	if in == nil {
		return nil
	}
	out := new(AzureConfigLoadBalancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureConfigNode) DeepCopyInto(out *AzureConfigNode) {
	*out = *in
	out.OSImage = in.OSImage
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureConfigNode.
func (in *AzureConfigNode) DeepCopy() *AzureConfigNode {
	if in == nil {
		return nil
	}
	out := new(AzureConfigNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureConfigOSImage) DeepCopyInto(out *AzureConfigOSImage) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureConfigOSImage.
func (in *AzureConfigOSImage) DeepCopy() *AzureConfigOSImage {
	if in == nil {
		return nil
	}
	out := new(AzureConfigOSImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureConfigResourceGroup) DeepCopyInto(out *AzureConfigResourceGroup) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureConfigResourceGroup.
func (in *AzureConfigResourceGroup) DeepCopy() *AzureConfigResourceGroup {
	if in == nil {
		return nil
	}
	out := new(AzureConfigResourceGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureConfigSpec) DeepCopyInto(out *AzureConfigSpec) {
	*out = *in
	out.KeyVault = in.KeyVault
	out.ResourceGroup = in.ResourceGroup
	out.Storage = in.Storage
	out.VirtualNetwork = in.VirtualNetwork
	if in.Masters != nil {
		in, out := &in.Masters, &out.Masters
		*out = make([]AzureConfigNode, len(*in))
		copy(*out, *in)
	}
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = make([]AzureConfigNode, len(*in))
		copy(*out, *in)
	}
	out.DNSZones = in.DNSZones
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureConfigSpec.
func (in *AzureConfigSpec) DeepCopy() *AzureConfigSpec {
	if in == nil {
		return nil
	}
	out := new(AzureConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureConfigStorage) DeepCopyInto(out *AzureConfigStorage) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureConfigStorage.
func (in *AzureConfigStorage) DeepCopy() *AzureConfigStorage {
	if in == nil {
		return nil
	}
	out := new(AzureConfigStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureConfigVirtualNetwork) DeepCopyInto(out *AzureConfigVirtualNetwork) {
	*out = *in
	out.LoadBalancer = in.LoadBalancer
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureConfigVirtualNetwork.
func (in *AzureConfigVirtualNetwork) DeepCopy() *AzureConfigVirtualNetwork {
	if in == nil {
		return nil
	}
	out := new(AzureConfigVirtualNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfig) DeepCopyInto(out *KVMConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfig.
func (in *KVMConfig) DeepCopy() *KVMConfig {
	if in == nil {
		return nil
	}
	out := new(KVMConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KVMConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigList) DeepCopyInto(out *KVMConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KVMConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigList.
func (in *KVMConfigList) DeepCopy() *KVMConfigList {
	if in == nil {
		return nil
	}
	out := new(KVMConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KVMConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigSpec) DeepCopyInto(out *KVMConfigSpec) {
	*out = *in
	in.Cluster.DeepCopyInto(&out.Cluster)
	in.KVMConfig.DeepCopyInto(&out.KVMConfig)
	out.VersionBundle = in.VersionBundle
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigSpec.
func (in *KVMConfigSpec) DeepCopy() *KVMConfigSpec {
	if in == nil {
		return nil
	}
	out := new(KVMConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigSpecCluster) DeepCopyInto(out *KVMConfigSpecCluster) {
	*out = *in
	out.Calico = in.Calico
	out.Customer = in.Customer
	out.Docker = in.Docker
	out.Etcd = in.Etcd
	in.Kubernetes.DeepCopyInto(&out.Kubernetes)
	if in.Masters != nil {
		in, out := &in.Masters, &out.Masters
		*out = make([]KVMConfigSpecClusterNode, len(*in))
		copy(*out, *in)
	}
	out.Vault = in.Vault
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = make([]KVMConfigSpecClusterNode, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigSpecCluster.
func (in *KVMConfigSpecCluster) DeepCopy() *KVMConfigSpecCluster {
	if in == nil {
		return nil
	}
	out := new(KVMConfigSpecCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigSpecClusterCalico) DeepCopyInto(out *KVMConfigSpecClusterCalico) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigSpecClusterCalico.
func (in *KVMConfigSpecClusterCalico) DeepCopy() *KVMConfigSpecClusterCalico {
	if in == nil {
		return nil
	}
	out := new(KVMConfigSpecClusterCalico)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigSpecClusterCustomer) DeepCopyInto(out *KVMConfigSpecClusterCustomer) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigSpecClusterCustomer.
func (in *KVMConfigSpecClusterCustomer) DeepCopy() *KVMConfigSpecClusterCustomer {
	if in == nil {
		return nil
	}
	out := new(KVMConfigSpecClusterCustomer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigSpecClusterDocker) DeepCopyInto(out *KVMConfigSpecClusterDocker) {
	*out = *in
	out.Daemon = in.Daemon
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigSpecClusterDocker.
func (in *KVMConfigSpecClusterDocker) DeepCopy() *KVMConfigSpecClusterDocker {
	if in == nil {
		return nil
	}
	out := new(KVMConfigSpecClusterDocker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigSpecClusterDockerDaemon) DeepCopyInto(out *KVMConfigSpecClusterDockerDaemon) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigSpecClusterDockerDaemon.
func (in *KVMConfigSpecClusterDockerDaemon) DeepCopy() *KVMConfigSpecClusterDockerDaemon {
	if in == nil {
		return nil
	}
	out := new(KVMConfigSpecClusterDockerDaemon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigSpecClusterEtcd) DeepCopyInto(out *KVMConfigSpecClusterEtcd) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigSpecClusterEtcd.
func (in *KVMConfigSpecClusterEtcd) DeepCopy() *KVMConfigSpecClusterEtcd {
	if in == nil {
		return nil
	}
	out := new(KVMConfigSpecClusterEtcd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigSpecClusterKubernetes) DeepCopyInto(out *KVMConfigSpecClusterKubernetes) {
	*out = *in
	in.API.DeepCopyInto(&out.API)
	in.DNS.DeepCopyInto(&out.DNS)
	out.Hyperkube = in.Hyperkube
	out.IngressController = in.IngressController
	out.Kubelet = in.Kubelet
	out.NetworkSetup = in.NetworkSetup
	in.SSH.DeepCopyInto(&out.SSH)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigSpecClusterKubernetes.
func (in *KVMConfigSpecClusterKubernetes) DeepCopy() *KVMConfigSpecClusterKubernetes {
	if in == nil {
		return nil
	}
	out := new(KVMConfigSpecClusterKubernetes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigSpecClusterKubernetesAPI) DeepCopyInto(out *KVMConfigSpecClusterKubernetesAPI) {
	*out = *in
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = make(net.IP, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigSpecClusterKubernetesAPI.
func (in *KVMConfigSpecClusterKubernetesAPI) DeepCopy() *KVMConfigSpecClusterKubernetesAPI {
	if in == nil {
		return nil
	}
	out := new(KVMConfigSpecClusterKubernetesAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigSpecClusterKubernetesDNS) DeepCopyInto(out *KVMConfigSpecClusterKubernetesDNS) {
	*out = *in
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = make(net.IP, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigSpecClusterKubernetesDNS.
func (in *KVMConfigSpecClusterKubernetesDNS) DeepCopy() *KVMConfigSpecClusterKubernetesDNS {
	if in == nil {
		return nil
	}
	out := new(KVMConfigSpecClusterKubernetesDNS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigSpecClusterKubernetesHyperkube) DeepCopyInto(out *KVMConfigSpecClusterKubernetesHyperkube) {
	*out = *in
	out.Docker = in.Docker
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigSpecClusterKubernetesHyperkube.
func (in *KVMConfigSpecClusterKubernetesHyperkube) DeepCopy() *KVMConfigSpecClusterKubernetesHyperkube {
	if in == nil {
		return nil
	}
	out := new(KVMConfigSpecClusterKubernetesHyperkube)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigSpecClusterKubernetesHyperkubeDocker) DeepCopyInto(out *KVMConfigSpecClusterKubernetesHyperkubeDocker) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigSpecClusterKubernetesHyperkubeDocker.
func (in *KVMConfigSpecClusterKubernetesHyperkubeDocker) DeepCopy() *KVMConfigSpecClusterKubernetesHyperkubeDocker {
	if in == nil {
		return nil
	}
	out := new(KVMConfigSpecClusterKubernetesHyperkubeDocker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigSpecClusterKubernetesIngressController) DeepCopyInto(out *KVMConfigSpecClusterKubernetesIngressController) {
	*out = *in
	out.Docker = in.Docker
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigSpecClusterKubernetesIngressController.
func (in *KVMConfigSpecClusterKubernetesIngressController) DeepCopy() *KVMConfigSpecClusterKubernetesIngressController {
	if in == nil {
		return nil
	}
	out := new(KVMConfigSpecClusterKubernetesIngressController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigSpecClusterKubernetesIngressControllerDocker) DeepCopyInto(out *KVMConfigSpecClusterKubernetesIngressControllerDocker) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigSpecClusterKubernetesIngressControllerDocker.
func (in *KVMConfigSpecClusterKubernetesIngressControllerDocker) DeepCopy() *KVMConfigSpecClusterKubernetesIngressControllerDocker {
	if in == nil {
		return nil
	}
	out := new(KVMConfigSpecClusterKubernetesIngressControllerDocker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigSpecClusterKubernetesKubelet) DeepCopyInto(out *KVMConfigSpecClusterKubernetesKubelet) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigSpecClusterKubernetesKubelet.
func (in *KVMConfigSpecClusterKubernetesKubelet) DeepCopy() *KVMConfigSpecClusterKubernetesKubelet {
	if in == nil {
		return nil
	}
	out := new(KVMConfigSpecClusterKubernetesKubelet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigSpecClusterKubernetesNetworkSetup) DeepCopyInto(out *KVMConfigSpecClusterKubernetesNetworkSetup) {
	*out = *in
	out.Docker = in.Docker
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigSpecClusterKubernetesNetworkSetup.
func (in *KVMConfigSpecClusterKubernetesNetworkSetup) DeepCopy() *KVMConfigSpecClusterKubernetesNetworkSetup {
	if in == nil {
		return nil
	}
	out := new(KVMConfigSpecClusterKubernetesNetworkSetup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigSpecClusterKubernetesNetworkSetupDocker) DeepCopyInto(out *KVMConfigSpecClusterKubernetesNetworkSetupDocker) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigSpecClusterKubernetesNetworkSetupDocker.
func (in *KVMConfigSpecClusterKubernetesNetworkSetupDocker) DeepCopy() *KVMConfigSpecClusterKubernetesNetworkSetupDocker {
	if in == nil {
		return nil
	}
	out := new(KVMConfigSpecClusterKubernetesNetworkSetupDocker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigSpecClusterKubernetesSSH) DeepCopyInto(out *KVMConfigSpecClusterKubernetesSSH) {
	*out = *in
	if in.UserList != nil {
		in, out := &in.UserList, &out.UserList
		*out = make([]KVMConfigSpecClusterKubernetesSSHUser, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigSpecClusterKubernetesSSH.
func (in *KVMConfigSpecClusterKubernetesSSH) DeepCopy() *KVMConfigSpecClusterKubernetesSSH {
	if in == nil {
		return nil
	}
	out := new(KVMConfigSpecClusterKubernetesSSH)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigSpecClusterKubernetesSSHUser) DeepCopyInto(out *KVMConfigSpecClusterKubernetesSSHUser) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigSpecClusterKubernetesSSHUser.
func (in *KVMConfigSpecClusterKubernetesSSHUser) DeepCopy() *KVMConfigSpecClusterKubernetesSSHUser {
	if in == nil {
		return nil
	}
	out := new(KVMConfigSpecClusterKubernetesSSHUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigSpecClusterNode) DeepCopyInto(out *KVMConfigSpecClusterNode) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigSpecClusterNode.
func (in *KVMConfigSpecClusterNode) DeepCopy() *KVMConfigSpecClusterNode {
	if in == nil {
		return nil
	}
	out := new(KVMConfigSpecClusterNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigSpecClusterVault) DeepCopyInto(out *KVMConfigSpecClusterVault) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigSpecClusterVault.
func (in *KVMConfigSpecClusterVault) DeepCopy() *KVMConfigSpecClusterVault {
	if in == nil {
		return nil
	}
	out := new(KVMConfigSpecClusterVault)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigSpecKVM) DeepCopyInto(out *KVMConfigSpecKVM) {
	*out = *in
	out.EndpointUpdater = in.EndpointUpdater
	out.K8sKVM = in.K8sKVM
	if in.Masters != nil {
		in, out := &in.Masters, &out.Masters
		*out = make([]KVMConfigSpecKVMNode, len(*in))
		copy(*out, *in)
	}
	out.Network = in.Network
	out.NodeController = in.NodeController
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = make([]KVMConfigSpecKVMNode, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigSpecKVM.
func (in *KVMConfigSpecKVM) DeepCopy() *KVMConfigSpecKVM {
	if in == nil {
		return nil
	}
	out := new(KVMConfigSpecKVM)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigSpecKVMEndpointUpdater) DeepCopyInto(out *KVMConfigSpecKVMEndpointUpdater) {
	*out = *in
	out.Docker = in.Docker
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigSpecKVMEndpointUpdater.
func (in *KVMConfigSpecKVMEndpointUpdater) DeepCopy() *KVMConfigSpecKVMEndpointUpdater {
	if in == nil {
		return nil
	}
	out := new(KVMConfigSpecKVMEndpointUpdater)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigSpecKVMEndpointUpdaterDocker) DeepCopyInto(out *KVMConfigSpecKVMEndpointUpdaterDocker) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigSpecKVMEndpointUpdaterDocker.
func (in *KVMConfigSpecKVMEndpointUpdaterDocker) DeepCopy() *KVMConfigSpecKVMEndpointUpdaterDocker {
	if in == nil {
		return nil
	}
	out := new(KVMConfigSpecKVMEndpointUpdaterDocker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigSpecKVMK8sKVM) DeepCopyInto(out *KVMConfigSpecKVMK8sKVM) {
	*out = *in
	out.Docker = in.Docker
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigSpecKVMK8sKVM.
func (in *KVMConfigSpecKVMK8sKVM) DeepCopy() *KVMConfigSpecKVMK8sKVM {
	if in == nil {
		return nil
	}
	out := new(KVMConfigSpecKVMK8sKVM)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigSpecKVMK8sKVMDocker) DeepCopyInto(out *KVMConfigSpecKVMK8sKVMDocker) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigSpecKVMK8sKVMDocker.
func (in *KVMConfigSpecKVMK8sKVMDocker) DeepCopy() *KVMConfigSpecKVMK8sKVMDocker {
	if in == nil {
		return nil
	}
	out := new(KVMConfigSpecKVMK8sKVMDocker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigSpecKVMNetwork) DeepCopyInto(out *KVMConfigSpecKVMNetwork) {
	*out = *in
	out.Flannel = in.Flannel
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigSpecKVMNetwork.
func (in *KVMConfigSpecKVMNetwork) DeepCopy() *KVMConfigSpecKVMNetwork {
	if in == nil {
		return nil
	}
	out := new(KVMConfigSpecKVMNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigSpecKVMNetworkFlannel) DeepCopyInto(out *KVMConfigSpecKVMNetworkFlannel) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigSpecKVMNetworkFlannel.
func (in *KVMConfigSpecKVMNetworkFlannel) DeepCopy() *KVMConfigSpecKVMNetworkFlannel {
	if in == nil {
		return nil
	}
	out := new(KVMConfigSpecKVMNetworkFlannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigSpecKVMNode) DeepCopyInto(out *KVMConfigSpecKVMNode) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigSpecKVMNode.
func (in *KVMConfigSpecKVMNode) DeepCopy() *KVMConfigSpecKVMNode {
	if in == nil {
		return nil
	}
	out := new(KVMConfigSpecKVMNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigSpecKVMNodeController) DeepCopyInto(out *KVMConfigSpecKVMNodeController) {
	*out = *in
	out.Docker = in.Docker
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigSpecKVMNodeController.
func (in *KVMConfigSpecKVMNodeController) DeepCopy() *KVMConfigSpecKVMNodeController {
	if in == nil {
		return nil
	}
	out := new(KVMConfigSpecKVMNodeController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigSpecKVMNodeControllerDocker) DeepCopyInto(out *KVMConfigSpecKVMNodeControllerDocker) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigSpecKVMNodeControllerDocker.
func (in *KVMConfigSpecKVMNodeControllerDocker) DeepCopy() *KVMConfigSpecKVMNodeControllerDocker {
	if in == nil {
		return nil
	}
	out := new(KVMConfigSpecKVMNodeControllerDocker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMConfigSpecVersionBundle) DeepCopyInto(out *KVMConfigSpecVersionBundle) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMConfigSpecVersionBundle.
func (in *KVMConfigSpecVersionBundle) DeepCopy() *KVMConfigSpecVersionBundle {
	if in == nil {
		return nil
	}
	out := new(KVMConfigSpecVersionBundle)
	in.DeepCopyInto(out)
	return out
}
