apiVersion: v1
kind: Secret
metadata:
  labels:
    clusterID: {{.Values.cluster.id}}
    clusterKey: encryption
  name: {{.Values.cluster.id}}-encryption
type: Opaque
data:
  encryption: {{.Values.encryptionKey}}
