resources:
  - ../../../v1/cluster.x-k8s.io_clusters.yaml
patchesJson6902:
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: clusters.cluster.x-k8s.io
    path: patch.yaml
