- op: replace
  path: /spec/conversion
  value:
    strategy: Webhook
    webhook:
      clientConfig:
        caBundle: Cg==
        service:
          name: cluster-api-core-unique-webhook
          namespace: giantswarm
          path: /convert
      conversionReviewVersions:
        - v1
        - v1beta1
