/*
Copyright 2020 Giant Swarm GmbH.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	v1alpha3 "github.com/giantswarm/apiextensions/pkg/apis/infrastructure/v1alpha3"
)

// FakeAzureControlPlanes implements AzureControlPlaneInterface
type FakeAzureControlPlanes struct {
	Fake *FakeInfrastructureV1alpha3
	ns   string
}

var azurecontrolplanesResource = schema.GroupVersionResource{Group: "infrastructure.giantswarm.io", Version: "v1alpha3", Resource: "azurecontrolplanes"}

var azurecontrolplanesKind = schema.GroupVersionKind{Group: "infrastructure.giantswarm.io", Version: "v1alpha3", Kind: "AzureControlPlane"}

// Get takes name of the azureControlPlane, and returns the corresponding azureControlPlane object, and an error if there is any.
func (c *FakeAzureControlPlanes) Get(name string, options v1.GetOptions) (result *v1alpha3.AzureControlPlane, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(azurecontrolplanesResource, c.ns, name), &v1alpha3.AzureControlPlane{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha3.AzureControlPlane), err
}

// List takes label and field selectors, and returns the list of AzureControlPlanes that match those selectors.
func (c *FakeAzureControlPlanes) List(opts v1.ListOptions) (result *v1alpha3.AzureControlPlaneList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(azurecontrolplanesResource, azurecontrolplanesKind, c.ns, opts), &v1alpha3.AzureControlPlaneList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha3.AzureControlPlaneList{ListMeta: obj.(*v1alpha3.AzureControlPlaneList).ListMeta}
	for _, item := range obj.(*v1alpha3.AzureControlPlaneList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested azureControlPlanes.
func (c *FakeAzureControlPlanes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(azurecontrolplanesResource, c.ns, opts))

}

// Create takes the representation of a azureControlPlane and creates it.  Returns the server's representation of the azureControlPlane, and an error, if there is any.
func (c *FakeAzureControlPlanes) Create(azureControlPlane *v1alpha3.AzureControlPlane) (result *v1alpha3.AzureControlPlane, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(azurecontrolplanesResource, c.ns, azureControlPlane), &v1alpha3.AzureControlPlane{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha3.AzureControlPlane), err
}

// Update takes the representation of a azureControlPlane and updates it. Returns the server's representation of the azureControlPlane, and an error, if there is any.
func (c *FakeAzureControlPlanes) Update(azureControlPlane *v1alpha3.AzureControlPlane) (result *v1alpha3.AzureControlPlane, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(azurecontrolplanesResource, c.ns, azureControlPlane), &v1alpha3.AzureControlPlane{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha3.AzureControlPlane), err
}

// Delete takes name of the azureControlPlane and deletes it. Returns an error if one occurs.
func (c *FakeAzureControlPlanes) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(azurecontrolplanesResource, c.ns, name), &v1alpha3.AzureControlPlane{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAzureControlPlanes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(azurecontrolplanesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha3.AzureControlPlaneList{})
	return err
}

// Patch applies the patch and returns the patched azureControlPlane.
func (c *FakeAzureControlPlanes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha3.AzureControlPlane, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(azurecontrolplanesResource, c.ns, name, pt, data, subresources...), &v1alpha3.AzureControlPlane{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha3.AzureControlPlane), err
}
