apiVersion: "core.giantswarm.io/v1alpha1"
kind: CertConfig
metadata:
  name: "{{.Values.clusterName}}-calico"
  namespace: "default"
  labels:
    clusterID: "{{.Values.clusterName}}"
    clusterComponent: "calico"
spec:
  cert:
    clusterID: "{{.Values.clusterName}}"
    clusterComponent: "calico"
    commonName: "calico.{{.Values.clusterName}}.k8s.{{.Values.commonDomain}}"
    altNames:
    ipSans:
    ttl: "720h"
    allowBareDomains: false
    organizations:
  versionBundle:
    version: 0.1.0
