apiVersion: "core.giantswarm.io/v1alpha1"
kind: CertConfig
metadata:
  name: "{{.Values.clusterName}}-worker"
  namespace: "default"
  labels:
    clusterID: "{{.Values.clusterName}}"
    clusterComponent: "worker"
spec:
  cert:
    clusterID: "{{.Values.clusterName}}"
    clusterComponent: "worker"
    commonName: "worker.{{.Values.clusterName}}.{{.Values.commonDomain}}"
    altNames:
    - "{{.Values.clusterName}}.{{.Values.commonDomain}}"
    - "k8s-master-vm"
    - "kubernetes"
    - "kubernetes.default"
    - "kubernetes.default.svc"
    - "kubernetes.default.svc.cluster.local"
    ipSans:
    ttl: "720h"
    allowBareDomains: true
    organizations:
  versionBundle:
    version: 0.1.0
