/*
Copyright 2019 Giant Swarm GmbH.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/giantswarm/apiextensions/pkg/apis/example/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSearchIndexes implements SearchIndexInterface
type FakeSearchIndexes struct {
	Fake *FakeExampleV1alpha1
	ns   string
}

var searchindexesResource = schema.GroupVersionResource{Group: "example.giantswarm.io", Version: "v1alpha1", Resource: "searchindexes"}

var searchindexesKind = schema.GroupVersionKind{Group: "example.giantswarm.io", Version: "v1alpha1", Kind: "SearchIndex"}

// Get takes name of the searchIndex, and returns the corresponding searchIndex object, and an error if there is any.
func (c *FakeSearchIndexes) Get(name string, options v1.GetOptions) (result *v1alpha1.SearchIndex, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(searchindexesResource, c.ns, name), &v1alpha1.SearchIndex{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SearchIndex), err
}

// List takes label and field selectors, and returns the list of SearchIndexes that match those selectors.
func (c *FakeSearchIndexes) List(opts v1.ListOptions) (result *v1alpha1.SearchIndexList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(searchindexesResource, searchindexesKind, c.ns, opts), &v1alpha1.SearchIndexList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SearchIndexList{ListMeta: obj.(*v1alpha1.SearchIndexList).ListMeta}
	for _, item := range obj.(*v1alpha1.SearchIndexList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested searchIndexes.
func (c *FakeSearchIndexes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(searchindexesResource, c.ns, opts))

}

// Create takes the representation of a searchIndex and creates it.  Returns the server's representation of the searchIndex, and an error, if there is any.
func (c *FakeSearchIndexes) Create(searchIndex *v1alpha1.SearchIndex) (result *v1alpha1.SearchIndex, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(searchindexesResource, c.ns, searchIndex), &v1alpha1.SearchIndex{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SearchIndex), err
}

// Update takes the representation of a searchIndex and updates it. Returns the server's representation of the searchIndex, and an error, if there is any.
func (c *FakeSearchIndexes) Update(searchIndex *v1alpha1.SearchIndex) (result *v1alpha1.SearchIndex, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(searchindexesResource, c.ns, searchIndex), &v1alpha1.SearchIndex{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SearchIndex), err
}

// Delete takes name of the searchIndex and deletes it. Returns an error if one occurs.
func (c *FakeSearchIndexes) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(searchindexesResource, c.ns, name), &v1alpha1.SearchIndex{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSearchIndexes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(searchindexesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.SearchIndexList{})
	return err
}

// Patch applies the patch and returns the patched searchIndex.
func (c *FakeSearchIndexes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SearchIndex, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(searchindexesResource, c.ns, name, pt, data, subresources...), &v1alpha1.SearchIndex{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SearchIndex), err
}
