/*
Copyright 2019 Giant Swarm GmbH.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/giantswarm/apiextensions/pkg/apis/example/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeChaosMonkeyConfigs implements ChaosMonkeyConfigInterface
type FakeChaosMonkeyConfigs struct {
	Fake *FakeExampleV1alpha1
	ns   string
}

var chaosmonkeyconfigsResource = schema.GroupVersionResource{Group: "example.giantswarm.io", Version: "v1alpha1", Resource: "chaosmonkeyconfigs"}

var chaosmonkeyconfigsKind = schema.GroupVersionKind{Group: "example.giantswarm.io", Version: "v1alpha1", Kind: "ChaosMonkeyConfig"}

// Get takes name of the chaosMonkeyConfig, and returns the corresponding chaosMonkeyConfig object, and an error if there is any.
func (c *FakeChaosMonkeyConfigs) Get(name string, options v1.GetOptions) (result *v1alpha1.ChaosMonkeyConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(chaosmonkeyconfigsResource, c.ns, name), &v1alpha1.ChaosMonkeyConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChaosMonkeyConfig), err
}

// List takes label and field selectors, and returns the list of ChaosMonkeyConfigs that match those selectors.
func (c *FakeChaosMonkeyConfigs) List(opts v1.ListOptions) (result *v1alpha1.ChaosMonkeyConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(chaosmonkeyconfigsResource, chaosmonkeyconfigsKind, c.ns, opts), &v1alpha1.ChaosMonkeyConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ChaosMonkeyConfigList{ListMeta: obj.(*v1alpha1.ChaosMonkeyConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.ChaosMonkeyConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested chaosMonkeyConfigs.
func (c *FakeChaosMonkeyConfigs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(chaosmonkeyconfigsResource, c.ns, opts))

}

// Create takes the representation of a chaosMonkeyConfig and creates it.  Returns the server's representation of the chaosMonkeyConfig, and an error, if there is any.
func (c *FakeChaosMonkeyConfigs) Create(chaosMonkeyConfig *v1alpha1.ChaosMonkeyConfig) (result *v1alpha1.ChaosMonkeyConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(chaosmonkeyconfigsResource, c.ns, chaosMonkeyConfig), &v1alpha1.ChaosMonkeyConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChaosMonkeyConfig), err
}

// Update takes the representation of a chaosMonkeyConfig and updates it. Returns the server's representation of the chaosMonkeyConfig, and an error, if there is any.
func (c *FakeChaosMonkeyConfigs) Update(chaosMonkeyConfig *v1alpha1.ChaosMonkeyConfig) (result *v1alpha1.ChaosMonkeyConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(chaosmonkeyconfigsResource, c.ns, chaosMonkeyConfig), &v1alpha1.ChaosMonkeyConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChaosMonkeyConfig), err
}

// Delete takes name of the chaosMonkeyConfig and deletes it. Returns an error if one occurs.
func (c *FakeChaosMonkeyConfigs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(chaosmonkeyconfigsResource, c.ns, name), &v1alpha1.ChaosMonkeyConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeChaosMonkeyConfigs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(chaosmonkeyconfigsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ChaosMonkeyConfigList{})
	return err
}

// Patch applies the patch and returns the patched chaosMonkeyConfig.
func (c *FakeChaosMonkeyConfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ChaosMonkeyConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(chaosmonkeyconfigsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ChaosMonkeyConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChaosMonkeyConfig), err
}
