/*
Copyright 2021 Giant Swarm GmbH.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"

	v1alpha1 "github.com/giantswarm/apiextensions/v3/pkg/apis/core/v1alpha1"
	scheme "github.com/giantswarm/apiextensions/v3/pkg/clientset/versioned/scheme"
)

// CertConfigsGetter has a method to return a CertConfigInterface.
// A group's client should implement this interface.
type CertConfigsGetter interface {
	CertConfigs(namespace string) CertConfigInterface
}

// CertConfigInterface has methods to work with CertConfig resources.
type CertConfigInterface interface {
	Create(ctx context.Context, certConfig *v1alpha1.CertConfig, opts v1.CreateOptions) (*v1alpha1.CertConfig, error)
	Update(ctx context.Context, certConfig *v1alpha1.CertConfig, opts v1.UpdateOptions) (*v1alpha1.CertConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.CertConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.CertConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CertConfig, err error)
	CertConfigExpansion
}

// certConfigs implements CertConfigInterface
type certConfigs struct {
	client rest.Interface
	ns     string
}

// newCertConfigs returns a CertConfigs
func newCertConfigs(c *CoreV1alpha1Client, namespace string) *certConfigs {
	return &certConfigs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the certConfig, and returns the corresponding certConfig object, and an error if there is any.
func (c *certConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CertConfig, err error) {
	result = &v1alpha1.CertConfig{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("certconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CertConfigs that match those selectors.
func (c *certConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CertConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.CertConfigList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("certconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested certConfigs.
func (c *certConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("certconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a certConfig and creates it.  Returns the server's representation of the certConfig, and an error, if there is any.
func (c *certConfigs) Create(ctx context.Context, certConfig *v1alpha1.CertConfig, opts v1.CreateOptions) (result *v1alpha1.CertConfig, err error) {
	result = &v1alpha1.CertConfig{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("certconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(certConfig).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a certConfig and updates it. Returns the server's representation of the certConfig, and an error, if there is any.
func (c *certConfigs) Update(ctx context.Context, certConfig *v1alpha1.CertConfig, opts v1.UpdateOptions) (result *v1alpha1.CertConfig, err error) {
	result = &v1alpha1.CertConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("certconfigs").
		Name(certConfig.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(certConfig).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the certConfig and deletes it. Returns an error if one occurs.
func (c *certConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("certconfigs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *certConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("certconfigs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched certConfig.
func (c *certConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CertConfig, err error) {
	result = &v1alpha1.CertConfig{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("certconfigs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
