/*
Copyright 2020 Giant Swarm GmbH.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/giantswarm/apiextensions/pkg/apis/bootstrap/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeG8sBootstrapConfigs implements G8sBootstrapConfigInterface
type FakeG8sBootstrapConfigs struct {
	Fake *FakeBootstrapV1alpha2
	ns   string
}

var g8sbootstrapconfigsResource = schema.GroupVersionResource{Group: "bootstrap.giantswarm.io", Version: "v1alpha2", Resource: "g8sbootstrapconfigs"}

var g8sbootstrapconfigsKind = schema.GroupVersionKind{Group: "bootstrap.giantswarm.io", Version: "v1alpha2", Kind: "G8sBootstrapConfig"}

// Get takes name of the g8sBootstrapConfig, and returns the corresponding g8sBootstrapConfig object, and an error if there is any.
func (c *FakeG8sBootstrapConfigs) Get(name string, options v1.GetOptions) (result *v1alpha2.G8sBootstrapConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(g8sbootstrapconfigsResource, c.ns, name), &v1alpha2.G8sBootstrapConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.G8sBootstrapConfig), err
}

// List takes label and field selectors, and returns the list of G8sBootstrapConfigs that match those selectors.
func (c *FakeG8sBootstrapConfigs) List(opts v1.ListOptions) (result *v1alpha2.G8sBootstrapConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(g8sbootstrapconfigsResource, g8sbootstrapconfigsKind, c.ns, opts), &v1alpha2.G8sBootstrapConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.G8sBootstrapConfigList{ListMeta: obj.(*v1alpha2.G8sBootstrapConfigList).ListMeta}
	for _, item := range obj.(*v1alpha2.G8sBootstrapConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested g8sBootstrapConfigs.
func (c *FakeG8sBootstrapConfigs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(g8sbootstrapconfigsResource, c.ns, opts))

}

// Create takes the representation of a g8sBootstrapConfig and creates it.  Returns the server's representation of the g8sBootstrapConfig, and an error, if there is any.
func (c *FakeG8sBootstrapConfigs) Create(g8sBootstrapConfig *v1alpha2.G8sBootstrapConfig) (result *v1alpha2.G8sBootstrapConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(g8sbootstrapconfigsResource, c.ns, g8sBootstrapConfig), &v1alpha2.G8sBootstrapConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.G8sBootstrapConfig), err
}

// Update takes the representation of a g8sBootstrapConfig and updates it. Returns the server's representation of the g8sBootstrapConfig, and an error, if there is any.
func (c *FakeG8sBootstrapConfigs) Update(g8sBootstrapConfig *v1alpha2.G8sBootstrapConfig) (result *v1alpha2.G8sBootstrapConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(g8sbootstrapconfigsResource, c.ns, g8sBootstrapConfig), &v1alpha2.G8sBootstrapConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.G8sBootstrapConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeG8sBootstrapConfigs) UpdateStatus(g8sBootstrapConfig *v1alpha2.G8sBootstrapConfig) (*v1alpha2.G8sBootstrapConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(g8sbootstrapconfigsResource, "status", c.ns, g8sBootstrapConfig), &v1alpha2.G8sBootstrapConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.G8sBootstrapConfig), err
}

// Delete takes name of the g8sBootstrapConfig and deletes it. Returns an error if one occurs.
func (c *FakeG8sBootstrapConfigs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(g8sbootstrapconfigsResource, c.ns, name), &v1alpha2.G8sBootstrapConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeG8sBootstrapConfigs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(g8sbootstrapconfigsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha2.G8sBootstrapConfigList{})
	return err
}

// Patch applies the patch and returns the patched g8sBootstrapConfig.
func (c *FakeG8sBootstrapConfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.G8sBootstrapConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(g8sbootstrapconfigsResource, c.ns, name, pt, data, subresources...), &v1alpha2.G8sBootstrapConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.G8sBootstrapConfig), err
}
