/*
Copyright 2019 Giant Swarm GmbH.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/giantswarm/apiextensions/pkg/apis/provider/v1alpha1"
	scheme "github.com/giantswarm/apiextensions/pkg/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AWSTagListsGetter has a method to return a AWSTagListInterface.
// A group's client should implement this interface.
type AWSTagListsGetter interface {
	AWSTagLists(namespace string) AWSTagListInterface
}

// AWSTagListInterface has methods to work with AWSTagList resources.
type AWSTagListInterface interface {
	Create(*v1alpha1.AWSTagList) (*v1alpha1.AWSTagList, error)
	Update(*v1alpha1.AWSTagList) (*v1alpha1.AWSTagList, error)
	UpdateStatus(*v1alpha1.AWSTagList) (*v1alpha1.AWSTagList, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.AWSTagList, error)
	List(opts v1.ListOptions) (*v1alpha1.AWSTagListList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AWSTagList, err error)
	AWSTagListExpansion
}

// aWSTagLists implements AWSTagListInterface
type aWSTagLists struct {
	client rest.Interface
	ns     string
}

// newAWSTagLists returns a AWSTagLists
func newAWSTagLists(c *ProviderV1alpha1Client, namespace string) *aWSTagLists {
	return &aWSTagLists{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the aWSTagList, and returns the corresponding aWSTagList object, and an error if there is any.
func (c *aWSTagLists) Get(name string, options v1.GetOptions) (result *v1alpha1.AWSTagList, err error) {
	result = &v1alpha1.AWSTagList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awstaglists").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AWSTagLists that match those selectors.
func (c *aWSTagLists) List(opts v1.ListOptions) (result *v1alpha1.AWSTagListList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AWSTagListList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awstaglists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested aWSTagLists.
func (c *aWSTagLists) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("awstaglists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a aWSTagList and creates it.  Returns the server's representation of the aWSTagList, and an error, if there is any.
func (c *aWSTagLists) Create(aWSTagList *v1alpha1.AWSTagList) (result *v1alpha1.AWSTagList, err error) {
	result = &v1alpha1.AWSTagList{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("awstaglists").
		Body(aWSTagList).
		Do().
		Into(result)
	return
}

// Update takes the representation of a aWSTagList and updates it. Returns the server's representation of the aWSTagList, and an error, if there is any.
func (c *aWSTagLists) Update(aWSTagList *v1alpha1.AWSTagList) (result *v1alpha1.AWSTagList, err error) {
	result = &v1alpha1.AWSTagList{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("awstaglists").
		Name(aWSTagList.Name).
		Body(aWSTagList).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *aWSTagLists) UpdateStatus(aWSTagList *v1alpha1.AWSTagList) (result *v1alpha1.AWSTagList, err error) {
	result = &v1alpha1.AWSTagList{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("awstaglists").
		Name(aWSTagList.Name).
		SubResource("status").
		Body(aWSTagList).
		Do().
		Into(result)
	return
}

// Delete takes name of the aWSTagList and deletes it. Returns an error if one occurs.
func (c *aWSTagLists) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awstaglists").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *aWSTagLists) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awstaglists").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched aWSTagList.
func (c *aWSTagLists) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AWSTagList, err error) {
	result = &v1alpha1.AWSTagList{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("awstaglists").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
