/*
Copyright 2020 Giant Swarm GmbH.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"

	v1alpha1 "github.com/giantswarm/apiextensions/pkg/apis/security/v1alpha1"
	scheme "github.com/giantswarm/apiextensions/pkg/clientset/versioned/scheme"
)

// OrganizationsGetter has a method to return a OrganizationInterface.
// A group's client should implement this interface.
type OrganizationsGetter interface {
	Organizations() OrganizationInterface
}

// OrganizationInterface has methods to work with Organization resources.
type OrganizationInterface interface {
	Create(*v1alpha1.Organization) (*v1alpha1.Organization, error)
	Update(*v1alpha1.Organization) (*v1alpha1.Organization, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Organization, error)
	List(opts v1.ListOptions) (*v1alpha1.OrganizationList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Organization, err error)
	OrganizationExpansion
}

// organizations implements OrganizationInterface
type organizations struct {
	client rest.Interface
}

// newOrganizations returns a Organizations
func newOrganizations(c *SecurityV1alpha1Client) *organizations {
	return &organizations{
		client: c.RESTClient(),
	}
}

// Get takes name of the organization, and returns the corresponding organization object, and an error if there is any.
func (c *organizations) Get(name string, options v1.GetOptions) (result *v1alpha1.Organization, err error) {
	result = &v1alpha1.Organization{}
	err = c.client.Get().
		Resource("organizations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Organizations that match those selectors.
func (c *organizations) List(opts v1.ListOptions) (result *v1alpha1.OrganizationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.OrganizationList{}
	err = c.client.Get().
		Resource("organizations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested organizations.
func (c *organizations) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("organizations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a organization and creates it.  Returns the server's representation of the organization, and an error, if there is any.
func (c *organizations) Create(organization *v1alpha1.Organization) (result *v1alpha1.Organization, err error) {
	result = &v1alpha1.Organization{}
	err = c.client.Post().
		Resource("organizations").
		Body(organization).
		Do().
		Into(result)
	return
}

// Update takes the representation of a organization and updates it. Returns the server's representation of the organization, and an error, if there is any.
func (c *organizations) Update(organization *v1alpha1.Organization) (result *v1alpha1.Organization, err error) {
	result = &v1alpha1.Organization{}
	err = c.client.Put().
		Resource("organizations").
		Name(organization.Name).
		Body(organization).
		Do().
		Into(result)
	return
}

// Delete takes name of the organization and deletes it. Returns an error if one occurs.
func (c *organizations) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("organizations").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *organizations) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("organizations").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched organization.
func (c *organizations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Organization, err error) {
	result = &v1alpha1.Organization{}
	err = c.client.Patch(pt).
		Resource("organizations").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
