//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 Giant Swarm GmbH.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSClusterConfig) DeepCopyInto(out *AWSClusterConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSClusterConfig.
func (in *AWSClusterConfig) DeepCopy() *AWSClusterConfig {
	if in == nil {
		return nil
	}
	out := new(AWSClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSClusterConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSClusterConfigList) DeepCopyInto(out *AWSClusterConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AWSClusterConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSClusterConfigList.
func (in *AWSClusterConfigList) DeepCopy() *AWSClusterConfigList {
	if in == nil {
		return nil
	}
	out := new(AWSClusterConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSClusterConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSClusterConfigSpec) DeepCopyInto(out *AWSClusterConfigSpec) {
	*out = *in
	in.Guest.DeepCopyInto(&out.Guest)
	out.VersionBundle = in.VersionBundle
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSClusterConfigSpec.
func (in *AWSClusterConfigSpec) DeepCopy() *AWSClusterConfigSpec {
	if in == nil {
		return nil
	}
	out := new(AWSClusterConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSClusterConfigSpecGuest) DeepCopyInto(out *AWSClusterConfigSpecGuest) {
	*out = *in
	in.ClusterGuestConfig.DeepCopyInto(&out.ClusterGuestConfig)
	out.CredentialSecret = in.CredentialSecret
	if in.Masters != nil {
		in, out := &in.Masters, &out.Masters
		*out = make([]AWSClusterConfigSpecGuestMaster, len(*in))
		copy(*out, *in)
	}
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = make([]AWSClusterConfigSpecGuestWorker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSClusterConfigSpecGuest.
func (in *AWSClusterConfigSpecGuest) DeepCopy() *AWSClusterConfigSpecGuest {
	if in == nil {
		return nil
	}
	out := new(AWSClusterConfigSpecGuest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSClusterConfigSpecGuestCredentialSecret) DeepCopyInto(out *AWSClusterConfigSpecGuestCredentialSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSClusterConfigSpecGuestCredentialSecret.
func (in *AWSClusterConfigSpecGuestCredentialSecret) DeepCopy() *AWSClusterConfigSpecGuestCredentialSecret {
	if in == nil {
		return nil
	}
	out := new(AWSClusterConfigSpecGuestCredentialSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSClusterConfigSpecGuestMaster) DeepCopyInto(out *AWSClusterConfigSpecGuestMaster) {
	*out = *in
	out.AWSClusterConfigSpecGuestNode = in.AWSClusterConfigSpecGuestNode
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSClusterConfigSpecGuestMaster.
func (in *AWSClusterConfigSpecGuestMaster) DeepCopy() *AWSClusterConfigSpecGuestMaster {
	if in == nil {
		return nil
	}
	out := new(AWSClusterConfigSpecGuestMaster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSClusterConfigSpecGuestNode) DeepCopyInto(out *AWSClusterConfigSpecGuestNode) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSClusterConfigSpecGuestNode.
func (in *AWSClusterConfigSpecGuestNode) DeepCopy() *AWSClusterConfigSpecGuestNode {
	if in == nil {
		return nil
	}
	out := new(AWSClusterConfigSpecGuestNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSClusterConfigSpecGuestWorker) DeepCopyInto(out *AWSClusterConfigSpecGuestWorker) {
	*out = *in
	out.AWSClusterConfigSpecGuestNode = in.AWSClusterConfigSpecGuestNode
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSClusterConfigSpecGuestWorker.
func (in *AWSClusterConfigSpecGuestWorker) DeepCopy() *AWSClusterConfigSpecGuestWorker {
	if in == nil {
		return nil
	}
	out := new(AWSClusterConfigSpecGuestWorker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSClusterConfigSpecVersionBundle) DeepCopyInto(out *AWSClusterConfigSpecVersionBundle) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSClusterConfigSpecVersionBundle.
func (in *AWSClusterConfigSpecVersionBundle) DeepCopy() *AWSClusterConfigSpecVersionBundle {
	if in == nil {
		return nil
	}
	out := new(AWSClusterConfigSpecVersionBundle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureClusterConfig) DeepCopyInto(out *AzureClusterConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureClusterConfig.
func (in *AzureClusterConfig) DeepCopy() *AzureClusterConfig {
	if in == nil {
		return nil
	}
	out := new(AzureClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureClusterConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureClusterConfigList) DeepCopyInto(out *AzureClusterConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureClusterConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureClusterConfigList.
func (in *AzureClusterConfigList) DeepCopy() *AzureClusterConfigList {
	if in == nil {
		return nil
	}
	out := new(AzureClusterConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureClusterConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureClusterConfigSpec) DeepCopyInto(out *AzureClusterConfigSpec) {
	*out = *in
	in.Guest.DeepCopyInto(&out.Guest)
	out.VersionBundle = in.VersionBundle
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureClusterConfigSpec.
func (in *AzureClusterConfigSpec) DeepCopy() *AzureClusterConfigSpec {
	if in == nil {
		return nil
	}
	out := new(AzureClusterConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureClusterConfigSpecGuest) DeepCopyInto(out *AzureClusterConfigSpecGuest) {
	*out = *in
	in.ClusterGuestConfig.DeepCopyInto(&out.ClusterGuestConfig)
	out.CredentialSecret = in.CredentialSecret
	if in.Masters != nil {
		in, out := &in.Masters, &out.Masters
		*out = make([]AzureClusterConfigSpecGuestMaster, len(*in))
		copy(*out, *in)
	}
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = make([]AzureClusterConfigSpecGuestWorker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureClusterConfigSpecGuest.
func (in *AzureClusterConfigSpecGuest) DeepCopy() *AzureClusterConfigSpecGuest {
	if in == nil {
		return nil
	}
	out := new(AzureClusterConfigSpecGuest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureClusterConfigSpecGuestCredentialSecret) DeepCopyInto(out *AzureClusterConfigSpecGuestCredentialSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureClusterConfigSpecGuestCredentialSecret.
func (in *AzureClusterConfigSpecGuestCredentialSecret) DeepCopy() *AzureClusterConfigSpecGuestCredentialSecret {
	if in == nil {
		return nil
	}
	out := new(AzureClusterConfigSpecGuestCredentialSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureClusterConfigSpecGuestMaster) DeepCopyInto(out *AzureClusterConfigSpecGuestMaster) {
	*out = *in
	out.AzureClusterConfigSpecGuestNode = in.AzureClusterConfigSpecGuestNode
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureClusterConfigSpecGuestMaster.
func (in *AzureClusterConfigSpecGuestMaster) DeepCopy() *AzureClusterConfigSpecGuestMaster {
	if in == nil {
		return nil
	}
	out := new(AzureClusterConfigSpecGuestMaster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureClusterConfigSpecGuestNode) DeepCopyInto(out *AzureClusterConfigSpecGuestNode) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureClusterConfigSpecGuestNode.
func (in *AzureClusterConfigSpecGuestNode) DeepCopy() *AzureClusterConfigSpecGuestNode {
	if in == nil {
		return nil
	}
	out := new(AzureClusterConfigSpecGuestNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureClusterConfigSpecGuestWorker) DeepCopyInto(out *AzureClusterConfigSpecGuestWorker) {
	*out = *in
	out.AzureClusterConfigSpecGuestNode = in.AzureClusterConfigSpecGuestNode
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureClusterConfigSpecGuestWorker.
func (in *AzureClusterConfigSpecGuestWorker) DeepCopy() *AzureClusterConfigSpecGuestWorker {
	if in == nil {
		return nil
	}
	out := new(AzureClusterConfigSpecGuestWorker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureClusterConfigSpecVersionBundle) DeepCopyInto(out *AzureClusterConfigSpecVersionBundle) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureClusterConfigSpecVersionBundle.
func (in *AzureClusterConfigSpecVersionBundle) DeepCopy() *AzureClusterConfigSpecVersionBundle {
	if in == nil {
		return nil
	}
	out := new(AzureClusterConfigSpecVersionBundle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertConfig) DeepCopyInto(out *CertConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertConfig.
func (in *CertConfig) DeepCopy() *CertConfig {
	if in == nil {
		return nil
	}
	out := new(CertConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertConfigList) DeepCopyInto(out *CertConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CertConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertConfigList.
func (in *CertConfigList) DeepCopy() *CertConfigList {
	if in == nil {
		return nil
	}
	out := new(CertConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertConfigSpec) DeepCopyInto(out *CertConfigSpec) {
	*out = *in
	in.Cert.DeepCopyInto(&out.Cert)
	out.VersionBundle = in.VersionBundle
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertConfigSpec.
func (in *CertConfigSpec) DeepCopy() *CertConfigSpec {
	if in == nil {
		return nil
	}
	out := new(CertConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertConfigSpecCert) DeepCopyInto(out *CertConfigSpecCert) {
	*out = *in
	if in.AltNames != nil {
		in, out := &in.AltNames, &out.AltNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IPSANs != nil {
		in, out := &in.IPSANs, &out.IPSANs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Organizations != nil {
		in, out := &in.Organizations, &out.Organizations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertConfigSpecCert.
func (in *CertConfigSpecCert) DeepCopy() *CertConfigSpecCert {
	if in == nil {
		return nil
	}
	out := new(CertConfigSpecCert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertConfigSpecVersionBundle) DeepCopyInto(out *CertConfigSpecVersionBundle) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertConfigSpecVersionBundle.
func (in *CertConfigSpecVersionBundle) DeepCopy() *CertConfigSpecVersionBundle {
	if in == nil {
		return nil
	}
	out := new(CertConfigSpecVersionBundle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChartConfig) DeepCopyInto(out *ChartConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChartConfig.
func (in *ChartConfig) DeepCopy() *ChartConfig {
	if in == nil {
		return nil
	}
	out := new(ChartConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChartConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChartConfigList) DeepCopyInto(out *ChartConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ChartConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChartConfigList.
func (in *ChartConfigList) DeepCopy() *ChartConfigList {
	if in == nil {
		return nil
	}
	out := new(ChartConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChartConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChartConfigSpec) DeepCopyInto(out *ChartConfigSpec) {
	*out = *in
	out.Chart = in.Chart
	out.VersionBundle = in.VersionBundle
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChartConfigSpec.
func (in *ChartConfigSpec) DeepCopy() *ChartConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ChartConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChartConfigSpecChart) DeepCopyInto(out *ChartConfigSpecChart) {
	*out = *in
	out.ConfigMap = in.ConfigMap
	out.UserConfigMap = in.UserConfigMap
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChartConfigSpecChart.
func (in *ChartConfigSpecChart) DeepCopy() *ChartConfigSpecChart {
	if in == nil {
		return nil
	}
	out := new(ChartConfigSpecChart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChartConfigSpecConfigMap) DeepCopyInto(out *ChartConfigSpecConfigMap) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChartConfigSpecConfigMap.
func (in *ChartConfigSpecConfigMap) DeepCopy() *ChartConfigSpecConfigMap {
	if in == nil {
		return nil
	}
	out := new(ChartConfigSpecConfigMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChartConfigSpecSecret) DeepCopyInto(out *ChartConfigSpecSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChartConfigSpecSecret.
func (in *ChartConfigSpecSecret) DeepCopy() *ChartConfigSpecSecret {
	if in == nil {
		return nil
	}
	out := new(ChartConfigSpecSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChartConfigSpecVersionBundle) DeepCopyInto(out *ChartConfigSpecVersionBundle) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChartConfigSpecVersionBundle.
func (in *ChartConfigSpecVersionBundle) DeepCopy() *ChartConfigSpecVersionBundle {
	if in == nil {
		return nil
	}
	out := new(ChartConfigSpecVersionBundle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChartConfigStatus) DeepCopyInto(out *ChartConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChartConfigStatus.
func (in *ChartConfigStatus) DeepCopy() *ChartConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ChartConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGuestConfig) DeepCopyInto(out *ClusterGuestConfig) {
	*out = *in
	if in.VersionBundles != nil {
		in, out := &in.VersionBundles, &out.VersionBundles
		*out = make([]ClusterGuestConfigVersionBundle, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGuestConfig.
func (in *ClusterGuestConfig) DeepCopy() *ClusterGuestConfig {
	if in == nil {
		return nil
	}
	out := new(ClusterGuestConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGuestConfigVersionBundle) DeepCopyInto(out *ClusterGuestConfigVersionBundle) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGuestConfigVersionBundle.
func (in *ClusterGuestConfigVersionBundle) DeepCopy() *ClusterGuestConfigVersionBundle {
	if in == nil {
		return nil
	}
	out := new(ClusterGuestConfigVersionBundle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainerConfig) DeepCopyInto(out *DrainerConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainerConfig.
func (in *DrainerConfig) DeepCopy() *DrainerConfig {
	if in == nil {
		return nil
	}
	out := new(DrainerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DrainerConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainerConfigList) DeepCopyInto(out *DrainerConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DrainerConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainerConfigList.
func (in *DrainerConfigList) DeepCopy() *DrainerConfigList {
	if in == nil {
		return nil
	}
	out := new(DrainerConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DrainerConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainerConfigSpec) DeepCopyInto(out *DrainerConfigSpec) {
	*out = *in
	out.Guest = in.Guest
	out.VersionBundle = in.VersionBundle
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainerConfigSpec.
func (in *DrainerConfigSpec) DeepCopy() *DrainerConfigSpec {
	if in == nil {
		return nil
	}
	out := new(DrainerConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainerConfigSpecGuest) DeepCopyInto(out *DrainerConfigSpecGuest) {
	*out = *in
	out.Cluster = in.Cluster
	out.Node = in.Node
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainerConfigSpecGuest.
func (in *DrainerConfigSpecGuest) DeepCopy() *DrainerConfigSpecGuest {
	if in == nil {
		return nil
	}
	out := new(DrainerConfigSpecGuest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainerConfigSpecGuestCluster) DeepCopyInto(out *DrainerConfigSpecGuestCluster) {
	*out = *in
	out.API = in.API
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainerConfigSpecGuestCluster.
func (in *DrainerConfigSpecGuestCluster) DeepCopy() *DrainerConfigSpecGuestCluster {
	if in == nil {
		return nil
	}
	out := new(DrainerConfigSpecGuestCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainerConfigSpecGuestClusterAPI) DeepCopyInto(out *DrainerConfigSpecGuestClusterAPI) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainerConfigSpecGuestClusterAPI.
func (in *DrainerConfigSpecGuestClusterAPI) DeepCopy() *DrainerConfigSpecGuestClusterAPI {
	if in == nil {
		return nil
	}
	out := new(DrainerConfigSpecGuestClusterAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainerConfigSpecGuestNode) DeepCopyInto(out *DrainerConfigSpecGuestNode) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainerConfigSpecGuestNode.
func (in *DrainerConfigSpecGuestNode) DeepCopy() *DrainerConfigSpecGuestNode {
	if in == nil {
		return nil
	}
	out := new(DrainerConfigSpecGuestNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainerConfigSpecVersionBundle) DeepCopyInto(out *DrainerConfigSpecVersionBundle) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainerConfigSpecVersionBundle.
func (in *DrainerConfigSpecVersionBundle) DeepCopy() *DrainerConfigSpecVersionBundle {
	if in == nil {
		return nil
	}
	out := new(DrainerConfigSpecVersionBundle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainerConfigStatus) DeepCopyInto(out *DrainerConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]DrainerConfigStatusCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainerConfigStatus.
func (in *DrainerConfigStatus) DeepCopy() *DrainerConfigStatus {
	if in == nil {
		return nil
	}
	out := new(DrainerConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainerConfigStatusCondition) DeepCopyInto(out *DrainerConfigStatusCondition) {
	*out = *in
	in.LastHeartbeatTime.DeepCopyInto(&out.LastHeartbeatTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainerConfigStatusCondition.
func (in *DrainerConfigStatusCondition) DeepCopy() *DrainerConfigStatusCondition {
	if in == nil {
		return nil
	}
	out := new(DrainerConfigStatusCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlannelConfig) DeepCopyInto(out *FlannelConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlannelConfig.
func (in *FlannelConfig) DeepCopy() *FlannelConfig {
	if in == nil {
		return nil
	}
	out := new(FlannelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FlannelConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlannelConfigList) DeepCopyInto(out *FlannelConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FlannelConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlannelConfigList.
func (in *FlannelConfigList) DeepCopy() *FlannelConfigList {
	if in == nil {
		return nil
	}
	out := new(FlannelConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FlannelConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlannelConfigSpec) DeepCopyInto(out *FlannelConfigSpec) {
	*out = *in
	in.Bridge.DeepCopyInto(&out.Bridge)
	out.Cluster = in.Cluster
	out.Flannel = in.Flannel
	out.Health = in.Health
	out.VersionBundle = in.VersionBundle
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlannelConfigSpec.
func (in *FlannelConfigSpec) DeepCopy() *FlannelConfigSpec {
	if in == nil {
		return nil
	}
	out := new(FlannelConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlannelConfigSpecBridge) DeepCopyInto(out *FlannelConfigSpecBridge) {
	*out = *in
	out.Docker = in.Docker
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlannelConfigSpecBridge.
func (in *FlannelConfigSpecBridge) DeepCopy() *FlannelConfigSpecBridge {
	if in == nil {
		return nil
	}
	out := new(FlannelConfigSpecBridge)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlannelConfigSpecBridgeDocker) DeepCopyInto(out *FlannelConfigSpecBridgeDocker) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlannelConfigSpecBridgeDocker.
func (in *FlannelConfigSpecBridgeDocker) DeepCopy() *FlannelConfigSpecBridgeDocker {
	if in == nil {
		return nil
	}
	out := new(FlannelConfigSpecBridgeDocker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlannelConfigSpecBridgeSpec) DeepCopyInto(out *FlannelConfigSpecBridgeSpec) {
	*out = *in
	in.DNS.DeepCopyInto(&out.DNS)
	in.NTP.DeepCopyInto(&out.NTP)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlannelConfigSpecBridgeSpec.
func (in *FlannelConfigSpecBridgeSpec) DeepCopy() *FlannelConfigSpecBridgeSpec {
	if in == nil {
		return nil
	}
	out := new(FlannelConfigSpecBridgeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlannelConfigSpecBridgeSpecDNS) DeepCopyInto(out *FlannelConfigSpecBridgeSpecDNS) {
	*out = *in
	if in.Servers != nil {
		in, out := &in.Servers, &out.Servers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlannelConfigSpecBridgeSpecDNS.
func (in *FlannelConfigSpecBridgeSpecDNS) DeepCopy() *FlannelConfigSpecBridgeSpecDNS {
	if in == nil {
		return nil
	}
	out := new(FlannelConfigSpecBridgeSpecDNS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlannelConfigSpecBridgeSpecNTP) DeepCopyInto(out *FlannelConfigSpecBridgeSpecNTP) {
	*out = *in
	if in.Servers != nil {
		in, out := &in.Servers, &out.Servers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlannelConfigSpecBridgeSpecNTP.
func (in *FlannelConfigSpecBridgeSpecNTP) DeepCopy() *FlannelConfigSpecBridgeSpecNTP {
	if in == nil {
		return nil
	}
	out := new(FlannelConfigSpecBridgeSpecNTP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlannelConfigSpecCluster) DeepCopyInto(out *FlannelConfigSpecCluster) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlannelConfigSpecCluster.
func (in *FlannelConfigSpecCluster) DeepCopy() *FlannelConfigSpecCluster {
	if in == nil {
		return nil
	}
	out := new(FlannelConfigSpecCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlannelConfigSpecFlannel) DeepCopyInto(out *FlannelConfigSpecFlannel) {
	*out = *in
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlannelConfigSpecFlannel.
func (in *FlannelConfigSpecFlannel) DeepCopy() *FlannelConfigSpecFlannel {
	if in == nil {
		return nil
	}
	out := new(FlannelConfigSpecFlannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlannelConfigSpecFlannelSpec) DeepCopyInto(out *FlannelConfigSpecFlannelSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlannelConfigSpecFlannelSpec.
func (in *FlannelConfigSpecFlannelSpec) DeepCopy() *FlannelConfigSpecFlannelSpec {
	if in == nil {
		return nil
	}
	out := new(FlannelConfigSpecFlannelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlannelConfigSpecHealth) DeepCopyInto(out *FlannelConfigSpecHealth) {
	*out = *in
	out.Docker = in.Docker
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlannelConfigSpecHealth.
func (in *FlannelConfigSpecHealth) DeepCopy() *FlannelConfigSpecHealth {
	if in == nil {
		return nil
	}
	out := new(FlannelConfigSpecHealth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlannelConfigSpecHealthDocker) DeepCopyInto(out *FlannelConfigSpecHealthDocker) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlannelConfigSpecHealthDocker.
func (in *FlannelConfigSpecHealthDocker) DeepCopy() *FlannelConfigSpecHealthDocker {
	if in == nil {
		return nil
	}
	out := new(FlannelConfigSpecHealthDocker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlannelConfigSpecVersionBundle) DeepCopyInto(out *FlannelConfigSpecVersionBundle) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlannelConfigSpecVersionBundle.
func (in *FlannelConfigSpecVersionBundle) DeepCopy() *FlannelConfigSpecVersionBundle {
	if in == nil {
		return nil
	}
	out := new(FlannelConfigSpecVersionBundle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMClusterConfig) DeepCopyInto(out *KVMClusterConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMClusterConfig.
func (in *KVMClusterConfig) DeepCopy() *KVMClusterConfig {
	if in == nil {
		return nil
	}
	out := new(KVMClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KVMClusterConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMClusterConfigList) DeepCopyInto(out *KVMClusterConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KVMClusterConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMClusterConfigList.
func (in *KVMClusterConfigList) DeepCopy() *KVMClusterConfigList {
	if in == nil {
		return nil
	}
	out := new(KVMClusterConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KVMClusterConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMClusterConfigSpec) DeepCopyInto(out *KVMClusterConfigSpec) {
	*out = *in
	in.Guest.DeepCopyInto(&out.Guest)
	out.VersionBundle = in.VersionBundle
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMClusterConfigSpec.
func (in *KVMClusterConfigSpec) DeepCopy() *KVMClusterConfigSpec {
	if in == nil {
		return nil
	}
	out := new(KVMClusterConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMClusterConfigSpecGuest) DeepCopyInto(out *KVMClusterConfigSpecGuest) {
	*out = *in
	in.ClusterGuestConfig.DeepCopyInto(&out.ClusterGuestConfig)
	if in.Masters != nil {
		in, out := &in.Masters, &out.Masters
		*out = make([]KVMClusterConfigSpecGuestMaster, len(*in))
		copy(*out, *in)
	}
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = make([]KVMClusterConfigSpecGuestWorker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMClusterConfigSpecGuest.
func (in *KVMClusterConfigSpecGuest) DeepCopy() *KVMClusterConfigSpecGuest {
	if in == nil {
		return nil
	}
	out := new(KVMClusterConfigSpecGuest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMClusterConfigSpecGuestMaster) DeepCopyInto(out *KVMClusterConfigSpecGuestMaster) {
	*out = *in
	out.KVMClusterConfigSpecGuestNode = in.KVMClusterConfigSpecGuestNode
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMClusterConfigSpecGuestMaster.
func (in *KVMClusterConfigSpecGuestMaster) DeepCopy() *KVMClusterConfigSpecGuestMaster {
	if in == nil {
		return nil
	}
	out := new(KVMClusterConfigSpecGuestMaster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMClusterConfigSpecGuestNode) DeepCopyInto(out *KVMClusterConfigSpecGuestNode) {
	*out = *in
	out.MemorySizeGB = in.MemorySizeGB
	out.StorageSizeGB = in.StorageSizeGB
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMClusterConfigSpecGuestNode.
func (in *KVMClusterConfigSpecGuestNode) DeepCopy() *KVMClusterConfigSpecGuestNode {
	if in == nil {
		return nil
	}
	out := new(KVMClusterConfigSpecGuestNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMClusterConfigSpecGuestWorker) DeepCopyInto(out *KVMClusterConfigSpecGuestWorker) {
	*out = *in
	out.KVMClusterConfigSpecGuestNode = in.KVMClusterConfigSpecGuestNode
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMClusterConfigSpecGuestWorker.
func (in *KVMClusterConfigSpecGuestWorker) DeepCopy() *KVMClusterConfigSpecGuestWorker {
	if in == nil {
		return nil
	}
	out := new(KVMClusterConfigSpecGuestWorker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVMClusterConfigSpecVersionBundle) DeepCopyInto(out *KVMClusterConfigSpecVersionBundle) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVMClusterConfigSpecVersionBundle.
func (in *KVMClusterConfigSpecVersionBundle) DeepCopy() *KVMClusterConfigSpecVersionBundle {
	if in == nil {
		return nil
	}
	out := new(KVMClusterConfigSpecVersionBundle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Spark) DeepCopyInto(out *Spark) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Spark.
func (in *Spark) DeepCopy() *Spark {
	if in == nil {
		return nil
	}
	out := new(Spark)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Spark) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SparkList) DeepCopyInto(out *SparkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Spark, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SparkList.
func (in *SparkList) DeepCopy() *SparkList {
	if in == nil {
		return nil
	}
	out := new(SparkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SparkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SparkSpec) DeepCopyInto(out *SparkSpec) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SparkSpec.
func (in *SparkSpec) DeepCopy() *SparkSpec {
	if in == nil {
		return nil
	}
	out := new(SparkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SparkStatus) DeepCopyInto(out *SparkStatus) {
	*out = *in
	out.Verification = in.Verification
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SparkStatus.
func (in *SparkStatus) DeepCopy() *SparkStatus {
	if in == nil {
		return nil
	}
	out := new(SparkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SparkStatusVerification) DeepCopyInto(out *SparkStatusVerification) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SparkStatusVerification.
func (in *SparkStatusVerification) DeepCopy() *SparkStatusVerification {
	if in == nil {
		return nil
	}
	out := new(SparkStatusVerification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageConfig) DeepCopyInto(out *StorageConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageConfig.
func (in *StorageConfig) DeepCopy() *StorageConfig {
	if in == nil {
		return nil
	}
	out := new(StorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageConfigList) DeepCopyInto(out *StorageConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StorageConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageConfigList.
func (in *StorageConfigList) DeepCopy() *StorageConfigList {
	if in == nil {
		return nil
	}
	out := new(StorageConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageConfigSpec) DeepCopyInto(out *StorageConfigSpec) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageConfigSpec.
func (in *StorageConfigSpec) DeepCopy() *StorageConfigSpec {
	if in == nil {
		return nil
	}
	out := new(StorageConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageConfigSpecStorage) DeepCopyInto(out *StorageConfigSpecStorage) {
	*out = *in
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageConfigSpecStorage.
func (in *StorageConfigSpecStorage) DeepCopy() *StorageConfigSpecStorage {
	if in == nil {
		return nil
	}
	out := new(StorageConfigSpecStorage)
	in.DeepCopyInto(out)
	return out
}
