/*
Copyright 2019 Giant Swarm GmbH.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/giantswarm/apiextensions/pkg/apis/application/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAppPRDeployers implements AppPRDeployerInterface
type FakeAppPRDeployers struct {
	Fake *FakeApplicationV1alpha1
	ns   string
}

var appprdeployersResource = schema.GroupVersionResource{Group: "application.giantswarm.io", Version: "v1alpha1", Resource: "appprdeployers"}

var appprdeployersKind = schema.GroupVersionKind{Group: "application.giantswarm.io", Version: "v1alpha1", Kind: "AppPRDeployer"}

// Get takes name of the appPRDeployer, and returns the corresponding appPRDeployer object, and an error if there is any.
func (c *FakeAppPRDeployers) Get(name string, options v1.GetOptions) (result *v1alpha1.AppPRDeployer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(appprdeployersResource, c.ns, name), &v1alpha1.AppPRDeployer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AppPRDeployer), err
}

// List takes label and field selectors, and returns the list of AppPRDeployers that match those selectors.
func (c *FakeAppPRDeployers) List(opts v1.ListOptions) (result *v1alpha1.AppPRDeployerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(appprdeployersResource, appprdeployersKind, c.ns, opts), &v1alpha1.AppPRDeployerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AppPRDeployerList{ListMeta: obj.(*v1alpha1.AppPRDeployerList).ListMeta}
	for _, item := range obj.(*v1alpha1.AppPRDeployerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested appPRDeployers.
func (c *FakeAppPRDeployers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(appprdeployersResource, c.ns, opts))

}

// Create takes the representation of a appPRDeployer and creates it.  Returns the server's representation of the appPRDeployer, and an error, if there is any.
func (c *FakeAppPRDeployers) Create(appPRDeployer *v1alpha1.AppPRDeployer) (result *v1alpha1.AppPRDeployer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(appprdeployersResource, c.ns, appPRDeployer), &v1alpha1.AppPRDeployer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AppPRDeployer), err
}

// Update takes the representation of a appPRDeployer and updates it. Returns the server's representation of the appPRDeployer, and an error, if there is any.
func (c *FakeAppPRDeployers) Update(appPRDeployer *v1alpha1.AppPRDeployer) (result *v1alpha1.AppPRDeployer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(appprdeployersResource, c.ns, appPRDeployer), &v1alpha1.AppPRDeployer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AppPRDeployer), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAppPRDeployers) UpdateStatus(appPRDeployer *v1alpha1.AppPRDeployer) (*v1alpha1.AppPRDeployer, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(appprdeployersResource, "status", c.ns, appPRDeployer), &v1alpha1.AppPRDeployer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AppPRDeployer), err
}

// Delete takes name of the appPRDeployer and deletes it. Returns an error if one occurs.
func (c *FakeAppPRDeployers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(appprdeployersResource, c.ns, name), &v1alpha1.AppPRDeployer{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAppPRDeployers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(appprdeployersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.AppPRDeployerList{})
	return err
}

// Patch applies the patch and returns the patched appPRDeployer.
func (c *FakeAppPRDeployers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AppPRDeployer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(appprdeployersResource, c.ns, name, pt, data, subresources...), &v1alpha1.AppPRDeployer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AppPRDeployer), err
}
