// +build !ignore_autogenerated

/*
Copyright 2020 Giant Swarm GmbH.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha3

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureCluster) DeepCopyInto(out *AzureCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureCluster.
func (in *AzureCluster) DeepCopy() *AzureCluster {
	if in == nil {
		return nil
	}
	out := new(AzureCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureClusterList) DeepCopyInto(out *AzureClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureClusterList.
func (in *AzureClusterList) DeepCopy() *AzureClusterList {
	if in == nil {
		return nil
	}
	out := new(AzureClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureClusterSpec) DeepCopyInto(out *AzureClusterSpec) {
	*out = *in
	out.Cluster = in.Cluster
	out.Provider = in.Provider
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureClusterSpec.
func (in *AzureClusterSpec) DeepCopy() *AzureClusterSpec {
	if in == nil {
		return nil
	}
	out := new(AzureClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureClusterSpecCluster) DeepCopyInto(out *AzureClusterSpecCluster) {
	*out = *in
	out.DNS = in.DNS
	out.KubeProxy = in.KubeProxy
	out.OIDC = in.OIDC
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureClusterSpecCluster.
func (in *AzureClusterSpecCluster) DeepCopy() *AzureClusterSpecCluster {
	if in == nil {
		return nil
	}
	out := new(AzureClusterSpecCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureClusterSpecClusterDNS) DeepCopyInto(out *AzureClusterSpecClusterDNS) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureClusterSpecClusterDNS.
func (in *AzureClusterSpecClusterDNS) DeepCopy() *AzureClusterSpecClusterDNS {
	if in == nil {
		return nil
	}
	out := new(AzureClusterSpecClusterDNS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureClusterSpecClusterKubeProxy) DeepCopyInto(out *AzureClusterSpecClusterKubeProxy) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureClusterSpecClusterKubeProxy.
func (in *AzureClusterSpecClusterKubeProxy) DeepCopy() *AzureClusterSpecClusterKubeProxy {
	if in == nil {
		return nil
	}
	out := new(AzureClusterSpecClusterKubeProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureClusterSpecClusterOIDC) DeepCopyInto(out *AzureClusterSpecClusterOIDC) {
	*out = *in
	out.Claims = in.Claims
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureClusterSpecClusterOIDC.
func (in *AzureClusterSpecClusterOIDC) DeepCopy() *AzureClusterSpecClusterOIDC {
	if in == nil {
		return nil
	}
	out := new(AzureClusterSpecClusterOIDC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureClusterSpecClusterOIDCClaims) DeepCopyInto(out *AzureClusterSpecClusterOIDCClaims) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureClusterSpecClusterOIDCClaims.
func (in *AzureClusterSpecClusterOIDCClaims) DeepCopy() *AzureClusterSpecClusterOIDCClaims {
	if in == nil {
		return nil
	}
	out := new(AzureClusterSpecClusterOIDCClaims)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureClusterSpecProvider) DeepCopyInto(out *AzureClusterSpecProvider) {
	*out = *in
	out.CredentialSecret = in.CredentialSecret
	out.Master = in.Master
	out.Pods = in.Pods
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureClusterSpecProvider.
func (in *AzureClusterSpecProvider) DeepCopy() *AzureClusterSpecProvider {
	if in == nil {
		return nil
	}
	out := new(AzureClusterSpecProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureClusterSpecProviderCredentialSecret) DeepCopyInto(out *AzureClusterSpecProviderCredentialSecret) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureClusterSpecProviderCredentialSecret.
func (in *AzureClusterSpecProviderCredentialSecret) DeepCopy() *AzureClusterSpecProviderCredentialSecret {
	if in == nil {
		return nil
	}
	out := new(AzureClusterSpecProviderCredentialSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureClusterSpecProviderMaster) DeepCopyInto(out *AzureClusterSpecProviderMaster) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureClusterSpecProviderMaster.
func (in *AzureClusterSpecProviderMaster) DeepCopy() *AzureClusterSpecProviderMaster {
	if in == nil {
		return nil
	}
	out := new(AzureClusterSpecProviderMaster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureClusterSpecProviderPods) DeepCopyInto(out *AzureClusterSpecProviderPods) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureClusterSpecProviderPods.
func (in *AzureClusterSpecProviderPods) DeepCopy() *AzureClusterSpecProviderPods {
	if in == nil {
		return nil
	}
	out := new(AzureClusterSpecProviderPods)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureClusterStatus) DeepCopyInto(out *AzureClusterStatus) {
	*out = *in
	in.Cluster.DeepCopyInto(&out.Cluster)
	out.Provider = in.Provider
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureClusterStatus.
func (in *AzureClusterStatus) DeepCopy() *AzureClusterStatus {
	if in == nil {
		return nil
	}
	out := new(AzureClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureClusterStatusProvider) DeepCopyInto(out *AzureClusterStatusProvider) {
	*out = *in
	out.Network = in.Network
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureClusterStatusProvider.
func (in *AzureClusterStatusProvider) DeepCopy() *AzureClusterStatusProvider {
	if in == nil {
		return nil
	}
	out := new(AzureClusterStatusProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureClusterStatusProviderNetwork) DeepCopyInto(out *AzureClusterStatusProviderNetwork) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureClusterStatusProviderNetwork.
func (in *AzureClusterStatusProviderNetwork) DeepCopy() *AzureClusterStatusProviderNetwork {
	if in == nil {
		return nil
	}
	out := new(AzureClusterStatusProviderNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureControlPlane) DeepCopyInto(out *AzureControlPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureControlPlane.
func (in *AzureControlPlane) DeepCopy() *AzureControlPlane {
	if in == nil {
		return nil
	}
	out := new(AzureControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureControlPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureControlPlaneList) DeepCopyInto(out *AzureControlPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureControlPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureControlPlaneList.
func (in *AzureControlPlaneList) DeepCopy() *AzureControlPlaneList {
	if in == nil {
		return nil
	}
	out := new(AzureControlPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureControlPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureControlPlaneSpec) DeepCopyInto(out *AzureControlPlaneSpec) {
	*out = *in
	if in.AvailabilityZones != nil {
		in, out := &in.AvailabilityZones, &out.AvailabilityZones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureControlPlaneSpec.
func (in *AzureControlPlaneSpec) DeepCopy() *AzureControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(AzureControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureMachinePool) DeepCopyInto(out *AzureMachinePool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureMachinePool.
func (in *AzureMachinePool) DeepCopy() *AzureMachinePool {
	if in == nil {
		return nil
	}
	out := new(AzureMachinePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureMachinePool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureMachinePoolList) DeepCopyInto(out *AzureMachinePoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureMachinePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureMachinePoolList.
func (in *AzureMachinePoolList) DeepCopy() *AzureMachinePoolList {
	if in == nil {
		return nil
	}
	out := new(AzureMachinePoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureMachinePoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureMachinePoolSpec) DeepCopyInto(out *AzureMachinePoolSpec) {
	*out = *in
	out.NodePool = in.NodePool
	in.Provider.DeepCopyInto(&out.Provider)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureMachinePoolSpec.
func (in *AzureMachinePoolSpec) DeepCopy() *AzureMachinePoolSpec {
	if in == nil {
		return nil
	}
	out := new(AzureMachinePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureMachinePoolSpecInstanceDistribution) DeepCopyInto(out *AzureMachinePoolSpecInstanceDistribution) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureMachinePoolSpecInstanceDistribution.
func (in *AzureMachinePoolSpecInstanceDistribution) DeepCopy() *AzureMachinePoolSpecInstanceDistribution {
	if in == nil {
		return nil
	}
	out := new(AzureMachinePoolSpecInstanceDistribution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureMachinePoolSpecNodePool) DeepCopyInto(out *AzureMachinePoolSpecNodePool) {
	*out = *in
	out.Machine = in.Machine
	out.Scaling = in.Scaling
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureMachinePoolSpecNodePool.
func (in *AzureMachinePoolSpecNodePool) DeepCopy() *AzureMachinePoolSpecNodePool {
	if in == nil {
		return nil
	}
	out := new(AzureMachinePoolSpecNodePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureMachinePoolSpecNodePoolMachine) DeepCopyInto(out *AzureMachinePoolSpecNodePoolMachine) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureMachinePoolSpecNodePoolMachine.
func (in *AzureMachinePoolSpecNodePoolMachine) DeepCopy() *AzureMachinePoolSpecNodePoolMachine {
	if in == nil {
		return nil
	}
	out := new(AzureMachinePoolSpecNodePoolMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureMachinePoolSpecNodePoolScaling) DeepCopyInto(out *AzureMachinePoolSpecNodePoolScaling) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureMachinePoolSpecNodePoolScaling.
func (in *AzureMachinePoolSpecNodePoolScaling) DeepCopy() *AzureMachinePoolSpecNodePoolScaling {
	if in == nil {
		return nil
	}
	out := new(AzureMachinePoolSpecNodePoolScaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureMachinePoolSpecProvider) DeepCopyInto(out *AzureMachinePoolSpecProvider) {
	*out = *in
	if in.AvailabilityZones != nil {
		in, out := &in.AvailabilityZones, &out.AvailabilityZones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.InstanceDistribution = in.InstanceDistribution
	out.Worker = in.Worker
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureMachinePoolSpecProvider.
func (in *AzureMachinePoolSpecProvider) DeepCopy() *AzureMachinePoolSpecProvider {
	if in == nil {
		return nil
	}
	out := new(AzureMachinePoolSpecProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureMachinePoolSpecProviderWorker) DeepCopyInto(out *AzureMachinePoolSpecProviderWorker) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureMachinePoolSpecProviderWorker.
func (in *AzureMachinePoolSpecProviderWorker) DeepCopy() *AzureMachinePoolSpecProviderWorker {
	if in == nil {
		return nil
	}
	out := new(AzureMachinePoolSpecProviderWorker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureMachinePoolStatus) DeepCopyInto(out *AzureMachinePoolStatus) {
	*out = *in
	in.Provider.DeepCopyInto(&out.Provider)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureMachinePoolStatus.
func (in *AzureMachinePoolStatus) DeepCopy() *AzureMachinePoolStatus {
	if in == nil {
		return nil
	}
	out := new(AzureMachinePoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureMachinePoolStatusProvider) DeepCopyInto(out *AzureMachinePoolStatusProvider) {
	*out = *in
	in.Worker.DeepCopyInto(&out.Worker)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureMachinePoolStatusProvider.
func (in *AzureMachinePoolStatusProvider) DeepCopy() *AzureMachinePoolStatusProvider {
	if in == nil {
		return nil
	}
	out := new(AzureMachinePoolStatusProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureMachinePoolStatusProviderWorker) DeepCopyInto(out *AzureMachinePoolStatusProviderWorker) {
	*out = *in
	if in.InstanceTypes != nil {
		in, out := &in.InstanceTypes, &out.InstanceTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureMachinePoolStatusProviderWorker.
func (in *AzureMachinePoolStatusProviderWorker) DeepCopy() *AzureMachinePoolStatusProviderWorker {
	if in == nil {
		return nil
	}
	out := new(AzureMachinePoolStatusProviderWorker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonClusterStatus) DeepCopyInto(out *CommonClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]CommonClusterStatusCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]CommonClusterStatusVersion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonClusterStatus.
func (in *CommonClusterStatus) DeepCopy() *CommonClusterStatus {
	if in == nil {
		return nil
	}
	out := new(CommonClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonClusterStatusCondition) DeepCopyInto(out *CommonClusterStatusCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonClusterStatusCondition.
func (in *CommonClusterStatusCondition) DeepCopy() *CommonClusterStatusCondition {
	if in == nil {
		return nil
	}
	out := new(CommonClusterStatusCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonClusterStatusVersion) DeepCopyInto(out *CommonClusterStatusVersion) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonClusterStatusVersion.
func (in *CommonClusterStatusVersion) DeepCopy() *CommonClusterStatusVersion {
	if in == nil {
		return nil
	}
	out := new(CommonClusterStatusVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *G8sControlPlane) DeepCopyInto(out *G8sControlPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new G8sControlPlane.
func (in *G8sControlPlane) DeepCopy() *G8sControlPlane {
	if in == nil {
		return nil
	}
	out := new(G8sControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *G8sControlPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *G8sControlPlaneList) DeepCopyInto(out *G8sControlPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]G8sControlPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new G8sControlPlaneList.
func (in *G8sControlPlaneList) DeepCopy() *G8sControlPlaneList {
	if in == nil {
		return nil
	}
	out := new(G8sControlPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *G8sControlPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *G8sControlPlaneSpec) DeepCopyInto(out *G8sControlPlaneSpec) {
	*out = *in
	out.InfrastructureRef = in.InfrastructureRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new G8sControlPlaneSpec.
func (in *G8sControlPlaneSpec) DeepCopy() *G8sControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(G8sControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *G8sControlPlaneStatus) DeepCopyInto(out *G8sControlPlaneStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new G8sControlPlaneStatus.
func (in *G8sControlPlaneStatus) DeepCopy() *G8sControlPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(G8sControlPlaneStatus)
	in.DeepCopyInto(out)
	return out
}
