# This file contains configuration and metadata for the CRD schema documentation
# at https://docs.giantswarm.io/ui-api/management-api/crd/
#
# Only CRDs contained here will be published.
#
# Schema:
#
# .crds.*: Each key is a full CRD name.
# .crds.*.owner: List of URLs of teams owning the CRD.
# .crds.*.topics:
#   array of strings. Possible values:
#   - apps: related to managed apps
#   - managementcluster - deals with the management cluster.
#   - workloadcluster - deals with workload clusters.
# .crds.*.provider: array of strings. Possible values:
#   - aws
#   - azure
#   - kvm
# .crds.*.hidden: Set to true to disable in docs. Default is false.
# .crds.*.deprecation: If set, the CRD is marked as deprecated. Please also specify either .replaced_by or .info (but not both).
# .crds.*.deprecation.info: Text explaining the deprecation.
# .crds.*.deprecation.replaced_by.full_name: full name of the CRD to be used instead.
# .crds.*.deprecation.replaced_by.short_name: short name of the CRD to be used instead.
crds:
  appcatalogs.application.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-batman
    topics:
      - apps
    deprecation:
      replaced_by:
        full_name: catalogs.application.giantswarm.io
        short_name: Catalog
  appcatalogentries.application.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-batman
    topics:
      - apps
  apps.application.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-batman
    topics:
      - apps
  awsclusters.infrastructure.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    hidden: true
  awsclusters.infrastructure.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    provider:
      - aws
    topics:
      - workloadcluster
    deprecation:
      info: This CRD will be removed once Cluster API resources are used for all AWS workload clusters.
  awsclusterconfigs.core.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    hidden: true
  awsclustercontrolleridentities.infrastructure.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    hidden: true
  awsclusterroleidentities.infrastructure.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    hidden: true
  awsclusterstaticidentities.infrastructure.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    hidden: true
  awsconfigs.provider.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    hidden: true
  awscontrolplanes.infrastructure.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    provider:
      - aws
    topics:
      - workloadcluster
    deprecation:
      info: This CRD will be removed once Cluster API resources are used for all AWS workload clusters.
  awsfargateprofiles.infrastructure.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    hidden: true
  awsmachinedeployments.infrastructure.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    provider:
      - aws
    topics:
      - workloadcluster
  awsmachinepools.infrastructure.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    hidden: true
  awsmachines.infrastructure.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    hidden: true
  awsmachinetemplates.infrastructure.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    hidden: true
  awsmanagedclusters.infrastructure.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    hidden: true
  awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    hidden: true
  awsmanagedmachinepools.infrastructure.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    hidden: true
  azureassignedidentities.aadpodidentity.k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-celestial
    hidden: true
  azureclusteridentities.infrastructure.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-celestial
    hidden: true
  azureclusters.infrastructure.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-celestial
    provider:
      - azure
    topics:
      - workloadcluster
  azureclusterconfigs.core.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-celestial
    hidden: true
  azureconfigs.provider.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-celestial
    hidden: true
  azureidentities.aadpodidentity.k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-celestial
    hidden: true
  azureidentitybindings.aadpodidentity.k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-celestial
    hidden: true
  azuremachinepools.exp.infrastructure.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-celestial
    provider:
      - azure
    topics:
      - workloadcluster
  azuremachines.infrastructure.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-celestial
    provider:
      - azure
    topics:
      - workloadcluster
  azuremachinetemplates.infrastructure.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-celestial
    hidden: true
  azuremanagedclusters.exp.infrastructure.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-celestial
    hidden: true
  azuremanagedcontrolplanes.exp.infrastructure.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-celestial
    hidden: true
  azuremanagedmachinepools.exp.infrastructure.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-celestial
    hidden: true
  azurepodidentityexceptions.aadpodidentity.k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-celestial
    hidden: true
  azuretools.tooling.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-celestial
    hidden: true
  catalogs.application.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-batman
    topics:
      - apps
  certconfigs.core.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-ludacris
    topics:
      - managementcluster
      - workloadcluster
  charts.application.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-batman
    topics:
      - apps
  chartconfigs.core.giantswarm.io:
    hidden: true
  clusterresourcesetbindings.addons.cluster.x-k8s.io:
    hidden: true
  clusterresourcesets.addons.cluster.x-k8s.io:
    hidden: true
  clusters.core.giantswarm.io:
    hidden: true
  clusters.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-celestial
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    provider:
      - aws
      - azure
    topics:
      - workloadcluster
  configs.core.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-biscuit
    topics:
      - apps
      - managementcluster
  drainerconfigs.core.giantswarm.io:
    hidden: true
  draughtsmanconfigs.core.giantswarm.io:
    hidden: true
  eksconfigs.bootstrap.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    hidden: true
  eksconfigtemplates.bootstrap.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    hidden: true
  etcdbackups.backup.giantswarm.io:
    hidden: true
  flannelconfigs.core.giantswarm.io:
    hidden: true
  g8scontrolplanes.infrastructure.giantswarm.io:
    owner: 
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    provider:
      - aws
    topics:
      - workloadcluster
    deprecation:
      info: This CRD will be removed once Cluster API resources are used for all AWS workload clusters.
  haproxyloadbalancers.infrastructure.cluster.x-k8s.io:
    hidden: true
  ignitions.core.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-ludacris
    topics:
      - managementcluster
      - workloadcluster
  ingressconfigs.core.giantswarm.io:
    hidden: true
  kubeadmconfigs.bootstrap.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    hidden: true
  kubeadmconfigtemplates.bootstrap.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    hidden: true
  kubeadmcontrolplanes.controlplane.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    hidden: true
  kvmclusterconfigs.core.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-rocket
    provider:
      - kvm
    topics:
      - workloadcluster
  kvmconfigs.provider.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-rocket
    provider:
      - kvm
    topics:
      - workloadcluster
  machinedeployments.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    provider:
      - aws
    topics:
      - workloadcluster
  machinehealthchecks.cluster.x-k8s.io:
    hidden: true
  machinepools.exp.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-celestial
    provider:
      - azure
    topics:
      - workloadcluster
  machines.cluster.x-k8s.io:
    hidden: true
  machinesets.cluster.x-k8s.io:
    hidden: true
  memcachedconfigs.example.giantswarm.io:
    hidden: true
  networkpools.infrastructure.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    provider:
      - aws
    topics:
      - workloadcluster
  organizations.security.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-biscuit
    topics:
      - managementcluster
  releasecycles.release.giantswarm.io:
    hidden: true
  releases.release.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-ludacris
    topics:
      - managementcluster
      - workloadcluster
  silences.monitoring.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-atlas
    topics:
      - managementcluster
  sparks.core.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-celestial
    provider:
      - azure
    topics:
      - workloadcluster
  storageconfigs.core.giantswarm.io:
    hidden: true
    topics:
      - managementcluster
  vsphereclusters.infrastructure.cluster.x-k8s.io:
    hidden: true
  vspheremachines.infrastructure.cluster.x-k8s.io:
    hidden: true
  vspheremachinetemplates.infrastructure.cluster.x-k8s.io:
    hidden: true
  vspherevms.infrastructure.cluster.x-k8s.io:
    hidden: true
