# This file contains configuration and metadata for the CRD schema documentation
# at https://docs.giantswarm.io/ui-api/management-api/crd/
#
# Schema:
#
# .crds.*: Each key is a full CRD name.
# .crds.*.owner: List of URLs of teams owning the CRD.
# .crds.*.topics:
#   array of strings. Possible values:
#   - apps: related to managed apps
#   - managementcluster - deals with the management cluster.
#   - workloadcluster - deals with workload clusters.
# .crds.*.provider: array of strings. Possible values:
#   - aws
#   - azure
# .crds.*.publish: Set to false to disable in docs. Defaults is true.
#
crds:
  appcatalogs.application.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-batman
    topics:
      - apps
  appcatalogentries.application.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-batman
    topics:
      - apps
  apps.application.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-batman
    topics:
      - apps
  awsclusters.infrastructure.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    hidden: true
  awsclusters.infrastructure.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    provider:
      - aws
    topics:
      - workloadcluster
  awsclusterconfigs.core.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    hidden: true
  awsclusterroleidentities.infrastructure.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    hidden: true
  awsconfigs.provider.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    hidden: true
  awscontrolplanes.infrastructure.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    provider:
      - aws
    topics:
      - workloadcluster
  awsmachinedeployments.infrastructure.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    provider:
      - aws
    topics:
      - workloadcluster
  awsmachinepools.infrastructure.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    hidden: true
  awsmachinetemplates.infrastructure.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    hidden: true
  azureclusters.infrastructure.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-celestial
    provider:
      - azure
    topics:
      - workloadcluster
  azureclusterconfigs.core.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-celestial
    hidden: true
  azureconfigs.provider.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-celestial
    hidden: true
  azuremachinepools.exp.infrastructure.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-celestial
    provider:
      - azure
    topics:
      - workloadcluster
  azuremachines.infrastructure.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-celestial
    provider:
      - azure
    topics:
      - workloadcluster
  azuretools.tooling.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-celestial
    hidden: true
  certconfigs.core.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-ludacris
    topics:
      - managementcluster
      - workloadcluster
  charts.application.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-batman
    topics:
      - apps
  chartconfigs.core.giantswarm.io:
    hidden: true
  clusters.core.giantswarm.io:
    hidden: true
  clusters.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-celestial
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    provider:
      - aws
      - azure
    topics:
      - workloadcluster
  configs.core.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-biscuit
    topics:
      - apps
      - managementcluster
  drainerconfigs.core.giantswarm.io:
    hidden: true
  draughtsmanconfigs.core.giantswarm.io:
    hidden: true
  etcdbackups.backup.giantswarm.io:
    hidden: true
  flannelconfigs.core.giantswarm.io:
    hidden: true
  g8scontrolplanes.infrastructure.giantswarm.io:
    owner: 
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    provider:
      - aws
    topics:
      - workloadcluster
  ignitions.core.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-ludacris
    topics:
      - managementcluster
      - workloadcluster
  ingressconfigs.core.giantswarm.io:
    hidden: true
  kubeadmconfigs.bootstrap.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    hidden: true
  kubeadmcontrolplanes.controlplane.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    hidden: true
  kvmclusterconfigs.core.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-rocket
    provider:
      - kvm
    topics:
      - workloadcluster
  kvmconfigs.provider.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-rocket
    provider:
      - kvm
    topics:
      - workloadcluster
  machinepools.exp.cluster.x-k8s.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-celestial
    provider:
      - azure
    topics:
      - workloadcluster
  memcachedconfigs.example.giantswarm.io:
    hidden: true
  networkpools.infrastructure.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-firecracker
    provider:
      - aws
    topics:
      - workloadcluster
  organizations.security.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-biscuit
    topics:
      - managementcluster
  releasecycles.release.giantswarm.io:
    hidden: true
  releases.release.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-ludacris
    topics:
      - managementcluster
      - workloadcluster
  silences.monitoring.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-biscuit
    topics:
      - managementcluster
  sparks.core.giantswarm.io:
    owner:
      - https://github.com/orgs/giantswarm/teams/team-celestial
    provider:
      - azure
    topics:
      - workloadcluster
  storageconfigs.core.giantswarm.io:
    hidden: true
    topics:
      - managementcluster
  vsphereclusters.infrastructure.cluster.x-k8s.io:
    hidden: true
  vspheremachines.infrastructure.cluster.x-k8s.io:
    hidden: true
  vspheremachinetemplates.infrastructure.cluster.x-k8s.io:
    hidden: true
  vspherevms.infrastructure.cluster.x-k8s.io:
    hidden: true
