/*
Copyright 2019 Giant Swarm GmbH.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	"time"

	v1alpha2 "github.com/giantswarm/apiextensions/pkg/apis/bootstrap/v1alpha2"
	scheme "github.com/giantswarm/apiextensions/pkg/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// G8sBootstrapConfigsGetter has a method to return a G8sBootstrapConfigInterface.
// A group's client should implement this interface.
type G8sBootstrapConfigsGetter interface {
	G8sBootstrapConfigs(namespace string) G8sBootstrapConfigInterface
}

// G8sBootstrapConfigInterface has methods to work with G8sBootstrapConfig resources.
type G8sBootstrapConfigInterface interface {
	Create(*v1alpha2.G8sBootstrapConfig) (*v1alpha2.G8sBootstrapConfig, error)
	Update(*v1alpha2.G8sBootstrapConfig) (*v1alpha2.G8sBootstrapConfig, error)
	UpdateStatus(*v1alpha2.G8sBootstrapConfig) (*v1alpha2.G8sBootstrapConfig, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha2.G8sBootstrapConfig, error)
	List(opts v1.ListOptions) (*v1alpha2.G8sBootstrapConfigList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.G8sBootstrapConfig, err error)
	G8sBootstrapConfigExpansion
}

// g8sBootstrapConfigs implements G8sBootstrapConfigInterface
type g8sBootstrapConfigs struct {
	client rest.Interface
	ns     string
}

// newG8sBootstrapConfigs returns a G8sBootstrapConfigs
func newG8sBootstrapConfigs(c *ExampleV1alpha2Client, namespace string) *g8sBootstrapConfigs {
	return &g8sBootstrapConfigs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the g8sBootstrapConfig, and returns the corresponding g8sBootstrapConfig object, and an error if there is any.
func (c *g8sBootstrapConfigs) Get(name string, options v1.GetOptions) (result *v1alpha2.G8sBootstrapConfig, err error) {
	result = &v1alpha2.G8sBootstrapConfig{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("g8sbootstrapconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of G8sBootstrapConfigs that match those selectors.
func (c *g8sBootstrapConfigs) List(opts v1.ListOptions) (result *v1alpha2.G8sBootstrapConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha2.G8sBootstrapConfigList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("g8sbootstrapconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested g8sBootstrapConfigs.
func (c *g8sBootstrapConfigs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("g8sbootstrapconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a g8sBootstrapConfig and creates it.  Returns the server's representation of the g8sBootstrapConfig, and an error, if there is any.
func (c *g8sBootstrapConfigs) Create(g8sBootstrapConfig *v1alpha2.G8sBootstrapConfig) (result *v1alpha2.G8sBootstrapConfig, err error) {
	result = &v1alpha2.G8sBootstrapConfig{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("g8sbootstrapconfigs").
		Body(g8sBootstrapConfig).
		Do().
		Into(result)
	return
}

// Update takes the representation of a g8sBootstrapConfig and updates it. Returns the server's representation of the g8sBootstrapConfig, and an error, if there is any.
func (c *g8sBootstrapConfigs) Update(g8sBootstrapConfig *v1alpha2.G8sBootstrapConfig) (result *v1alpha2.G8sBootstrapConfig, err error) {
	result = &v1alpha2.G8sBootstrapConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("g8sbootstrapconfigs").
		Name(g8sBootstrapConfig.Name).
		Body(g8sBootstrapConfig).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *g8sBootstrapConfigs) UpdateStatus(g8sBootstrapConfig *v1alpha2.G8sBootstrapConfig) (result *v1alpha2.G8sBootstrapConfig, err error) {
	result = &v1alpha2.G8sBootstrapConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("g8sbootstrapconfigs").
		Name(g8sBootstrapConfig.Name).
		SubResource("status").
		Body(g8sBootstrapConfig).
		Do().
		Into(result)
	return
}

// Delete takes name of the g8sBootstrapConfig and deletes it. Returns an error if one occurs.
func (c *g8sBootstrapConfigs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("g8sbootstrapconfigs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *g8sBootstrapConfigs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("g8sbootstrapconfigs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched g8sBootstrapConfig.
func (c *g8sBootstrapConfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.G8sBootstrapConfig, err error) {
	result = &v1alpha2.G8sBootstrapConfig{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("g8sbootstrapconfigs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
