// +build !ignore_autogenerated

/*
Copyright 2019 Giant Swarm GmbH.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSpec) DeepCopyInto(out *ClusterSpec) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Cluster = in.Cluster
	out.Provider = in.Provider
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSpec.
func (in *ClusterSpec) DeepCopy() *ClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterSpec) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSpecCluster) DeepCopyInto(out *ClusterSpecCluster) {
	*out = *in
	out.DNS = in.DNS
	out.OIDC = in.OIDC
	out.VersionBundle = in.VersionBundle
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSpecCluster.
func (in *ClusterSpecCluster) DeepCopy() *ClusterSpecCluster {
	if in == nil {
		return nil
	}
	out := new(ClusterSpecCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSpecClusterDNS) DeepCopyInto(out *ClusterSpecClusterDNS) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSpecClusterDNS.
func (in *ClusterSpecClusterDNS) DeepCopy() *ClusterSpecClusterDNS {
	if in == nil {
		return nil
	}
	out := new(ClusterSpecClusterDNS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSpecClusterOIDC) DeepCopyInto(out *ClusterSpecClusterOIDC) {
	*out = *in
	out.Claims = in.Claims
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSpecClusterOIDC.
func (in *ClusterSpecClusterOIDC) DeepCopy() *ClusterSpecClusterOIDC {
	if in == nil {
		return nil
	}
	out := new(ClusterSpecClusterOIDC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSpecClusterOIDCClaims) DeepCopyInto(out *ClusterSpecClusterOIDCClaims) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSpecClusterOIDCClaims.
func (in *ClusterSpecClusterOIDCClaims) DeepCopy() *ClusterSpecClusterOIDCClaims {
	if in == nil {
		return nil
	}
	out := new(ClusterSpecClusterOIDCClaims)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSpecClusterVersionBundle) DeepCopyInto(out *ClusterSpecClusterVersionBundle) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSpecClusterVersionBundle.
func (in *ClusterSpecClusterVersionBundle) DeepCopy() *ClusterSpecClusterVersionBundle {
	if in == nil {
		return nil
	}
	out := new(ClusterSpecClusterVersionBundle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSpecProvider) DeepCopyInto(out *ClusterSpecProvider) {
	*out = *in
	out.CredentialSecret = in.CredentialSecret
	out.Master = in.Master
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSpecProvider.
func (in *ClusterSpecProvider) DeepCopy() *ClusterSpecProvider {
	if in == nil {
		return nil
	}
	out := new(ClusterSpecProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSpecProviderCredentialSecret) DeepCopyInto(out *ClusterSpecProviderCredentialSecret) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSpecProviderCredentialSecret.
func (in *ClusterSpecProviderCredentialSecret) DeepCopy() *ClusterSpecProviderCredentialSecret {
	if in == nil {
		return nil
	}
	out := new(ClusterSpecProviderCredentialSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSpecProviderMaster) DeepCopyInto(out *ClusterSpecProviderMaster) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSpecProviderMaster.
func (in *ClusterSpecProviderMaster) DeepCopy() *ClusterSpecProviderMaster {
	if in == nil {
		return nil
	}
	out := new(ClusterSpecProviderMaster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStatus) DeepCopyInto(out *ClusterStatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Cluster.DeepCopyInto(&out.Cluster)
	out.Provider = in.Provider
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStatus.
func (in *ClusterStatus) DeepCopy() *ClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStatusCluster) DeepCopyInto(out *ClusterStatusCluster) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ClusterStatusClusterCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]ClusterStatusClusterVersion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStatusCluster.
func (in *ClusterStatusCluster) DeepCopy() *ClusterStatusCluster {
	if in == nil {
		return nil
	}
	out := new(ClusterStatusCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStatusClusterCondition) DeepCopyInto(out *ClusterStatusClusterCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStatusClusterCondition.
func (in *ClusterStatusClusterCondition) DeepCopy() *ClusterStatusClusterCondition {
	if in == nil {
		return nil
	}
	out := new(ClusterStatusClusterCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStatusClusterVersion) DeepCopyInto(out *ClusterStatusClusterVersion) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStatusClusterVersion.
func (in *ClusterStatusClusterVersion) DeepCopy() *ClusterStatusClusterVersion {
	if in == nil {
		return nil
	}
	out := new(ClusterStatusClusterVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStatusProvider) DeepCopyInto(out *ClusterStatusProvider) {
	*out = *in
	out.Network = in.Network
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStatusProvider.
func (in *ClusterStatusProvider) DeepCopy() *ClusterStatusProvider {
	if in == nil {
		return nil
	}
	out := new(ClusterStatusProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStatusProviderNetwork) DeepCopyInto(out *ClusterStatusProviderNetwork) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStatusProviderNetwork.
func (in *ClusterStatusProviderNetwork) DeepCopy() *ClusterStatusProviderNetwork {
	if in == nil {
		return nil
	}
	out := new(ClusterStatusProviderNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeepCopyTime.
func (in *DeepCopyTime) DeepCopy() *DeepCopyTime {
	if in == nil {
		return nil
	}
	out := new(DeepCopyTime)
	in.DeepCopyInto(out)
	return out
}
